const langArr = {
  en: {
    description: 'System description ',
    presetation: 'Presetation',
    aboutApp: 'About the App',
    products: 'Products',
    contact: 'Contact us',
    bannerFirst: 'Meet Terma WiFi',
    bannerSecond: 'system products',
    slidTitleFirst: 'Terma SMART WiFi',
    slidTitleSecond: 'system description',
    firstSlideTitle: 'What is Terma SMART',
    firstSlideFirst:
      'It is a range of wirelessly controlled electric heating products.',
    firstSlideSecond:
      'It is an innovatively designed heating control system that can be easily adapted to your needs, including a choice of three types of devices and two types of sensors.',
    firstSlideThird:
      'It is a system that intelligently responds to changing conditions and communicates via the cloud.',
    ///
    secondSlideTitle: 'Remote control',
    secondSlideFirst:
      'A unique feature of the Smart system is that all devices communicate directly with the local (home) wifi router - thus no separate control module is needed, which means a serious saving when purchasing the system.',
    secondSlideSecond:
      'The system is managed by the free TERMA Smart control app, available for Android and iOS.',
    ///
    thirdSlideTitle: 'Design & construction',
    thirdSlideFirst:
      'Modern design emphasizes the uniqueness of each device, supports ergonomics of use, and binds the entire family of products.',
    thirdSlideSecond:
      'Elegant black and timeless white can be enriched with colored cover plates, and the multifunctional panel buttons will adjust to the mounting position of the device (horizontal or vertical).',
    thirdSlideThird:
      'The power output of the devices goes up to 2,000W, feature a few variants of electrical connections, and the VEO heating element is equipped with a unique Smart SPLIT connector.',
    ///
    fourthSlideTitle: 'Safety and SMART options',
    fourthSlideFirst:
      'The safety of the user is ensured by controllers equipped with temperature control algorithms, and each heating device has a specially selected thermal protection to prevent overheating. Predefined protection functions such as AntiFrost and the window opening detector remain active in the background.',
    fourthSlideSecond:
      'The self-learning Adaptiv Start function and the three operating modes (Comfort, Balance and Economic) support individual user preferences.',
    ///
    appTitle: 'Dedicated app',
    appParagraphFrist:
      'Gives the comfort of remote management of each Smart wi-fi heating device.',
    appParagraphSecond:
      'Facilitates home heating management by dividing the house into zones and setting separate system operating parameters for each of them.',
    appParagraphThird:
      'Provides tangible economic benefits by easily optimizing energy consumption for heating the house - using ready schedules or a simple scheduler helps to optimize the time and temperature settings of the system without losing the  thermal comfort.',
    appParagraphFourth:
      'Allows you to easily monitor the operation of devices throughout the house.',
    appParagraphFifth:
      'Allows you to easily monitor the costs generated by the system.',
    appParagraphSixth:
      "Allows flexible modification of the system's operating parameters by increasing the temperature when the User enters a specific zone or lowering it when away.",
    appParagraphSeventh:
      'Allows you to integrate any number of heating devices, making it perfect as a room temperature management system in flats and apartments.',

    productTitleFirst: 'The SMART',
    productTitleSecond: 'system products',
    veoTitle: 'VEO heating element',
    veoFirst:
      'VEO heater The sophisticated shape of the housing and an elegant front panel with a fading display conceal a seemingly delicate device. In fact, the remotely controlled VEO Smart heating element has a power of up to 2000 W, and the unique electrical connection allows it to be installed both vertically and horizontally, almost in any radiator with a heating medium.',
    veoSecond:
      'Basic adjustments (temperature and a simple timer) are available through the front panel, but the most convenient access to the full functionality of the system is provided by the TERMA Smart mobile application. The device works with window opening sensors and an additional temperature and humidity sensor from the SMART series.',

    heatingTitle: 'Thermostatic head VAZ',
    heatingFirst:
      'The sophisticated design of the SMART family, elegant black or the timeless white of the housing are the hallmarks of the VAZ thermostatic head. Together with the fading display, they add subtlety to the entire device. The head is powered by a high-performance battery cell, which is charged on a single charge for the entire heating season.',
    heatingSecond:
      'Extremely easy assembly and the auto-calibration procedure allow the head to be installed in almost any radiator and with any type of thermostatic valve. Basic regulations are available through the panel on the device, and the full functionality of the system is supported by the TERMA Smart mobile application. The device works with window opening sensors and an additional temperature and humidity sensor from the SMART series.',

    radiatorTitle: 'Radiator VOLTAN',
    radiatorFirst:
      'Electric convector VOLTAN - modern, easy to use, efficient, and at the same time very flat, almost indistinguishable against the background of the wall. The heater is equipped with a low-temperature 2000 W heat exchanger and an advanced controller with a self-learning control algorithm.',
    radiatorSecond:
      'Basic settings are available through the panel on the device, and the full functionality of the system is supported by the TERMA Smart mobile application. The device works with window opening sensors and an additional temperature and humidity sensor from the SMART series.',

    sensorTitle: 'Sensors VTS and VWS',
    sensorFirst:
      'VTS temperature and humidity sensor. An easy-to-install dual-function sensor constantly monitors the temperature and humidity in the room, sending information to the heating devices as soon as the temperature in the controlled zone changes by half a degree. ',
    sensorSecond:
      'VWS open window sensor. When the window is opened, the sensor sends information immediately to switch off heating in a given zone.',

    available: 'We are available 24/7',
    weWork:
      'We work from Monday to Friday from 07:00 to 18:00. In addition, we are available 24 hours a day, 7 days a week, using mobile phone numbers and via e-mail.',
    details: 'Company details',
    address: 'Czaple 100 80-298 Gdańsk Poland',
    nip: 'NIP:583-10-18-844',
    regon: 'REGON: 190558447',
    registration:
      'Company registration: E0001379W I Sąd Rej. w Gdańsku, VIII Wydz. Gosp.',
    KRS: 'KRS nr 0000069067',
    capital: 'Capital: 2 360 500PLN',
    account:
      'Bank account number: ING Bank Slaski S.A. Oddział w Gdańsku 88 1050 1764 1000 0023 0692 5997',
    form: 'Contact form',
    send: 'Send',
    terma: 'TERMA',
    machinery: 'CONSTRUCTION MACHINERY',
    services: 'INDUSTRIAL SERVICES',
    galvanizing: 'GALVANIZING',
    medical: 'MEDICAL PRODUCTS',
    sale: 'SALE OF RADIATORS',
    //
    thermostatic_head: 'Thermostatic Head',
    temperature_sensor: 'Temperature Sensor',
    electric_heater: 'Electric Heating Element',
    electric_radiator: 'Electric Radiator',
    'window-sensor': 'Window Opening Sensor',
    buy_sensor: 'Buy sensor',
    buy_termostatic_head: 'Buy thermostatic head',
    buy_heating_element: 'Buy heating element',
    download: 'Product card',
    VAZ: './product_card/VAZ-v1_EN_20211021_cibto.pdf',
    VTS: './product_card/VTS-v1_EN_20211021_cibto.pdf',
    VOS: './product_card/VOS-v1_EN_20211021_cibto.pdf',
    VEO: './product_card/VEO-v6_EN_20211020_cibto.pdf',
    terma_text: 'TERMA',
    terma_link: 'http://en.termagroup.pl/',
    machinery_text: 'MACHINERY',
    machinery_link: 'http://www.termamax.pl/en/glowna',
    services_text: ' ',
    services_link: ' ',
    galwanic_text: ' ',
    galwanic_link: ' ',
    medical_text: 'MEDICAL PRODUCTS',
    medical_link: 'https://www.termamed.pl/en',
  },
  de: {
    description: 'Systembeschreibung',
    presetation: 'Vorstellung',
    aboutApp: 'Über die Applikation',
    products: 'Produkte',
    contact: 'Kontakt',
    bannerFirst: 'Lernen Sie unsere WLAN',
    bannerSecond: 'Produktfamilie kennen',
    slidTitleFirst: 'Systembeschreibung',
    slidTitleSecond: 'Terma SMART WiFi',
    firstSlideTitle: 'Was ist Terma SMART',
    firstSlideFirst: 'Dies ist eine Auswahl ferngesteuerter Heizungsprodukte.',
    firstSlideSecond:
      'Es ist ein innovativ konzipiertes Raumheizungsregelsystem, das sich dank einer Auswahl von drei Gerätetypen und zwei Sensortypen leicht an Ihre individuellen Bedürfnisse anpassen lässt.',
    firstSlideThird:
      'Es ist ein System, das intelligent auf sich ändernde Bedingungen und Kommunikation über eine Cloud reagiert.',
    ///
    secondSlideTitle: 'Fernsteuerung',
    secondSlideFirst:
      'Ein einzigartiges Merkmal des Smart-Systems ist, dass alle Geräte direkt mit dem lokalen (Heim-)WLAN-Router kommunizieren - somit wird kein separates Steuermodul benötigt, was erhebliche Einsparungen beim Kauf des Systems bedeutet.',
    secondSlideSecond:
      'Zur Bedienung des Systems die kostenlose Steuerungs-App TERMA Smart benötigt, die für Android und iOS verfügbar ist.',
    ///
    thirdSlideTitle: 'Design und Konstruktion',
    thirdSlideFirst:
      'Das moderne Design unterstreicht die Einzigartigkeit jedes Geräts und unterstützt die Ergonomie der Bedienung, gleichzeitig verbindet es die gesamte Produktfamilie.',
    thirdSlideSecond:
      'Elegantes Schwarz und zeitloses Weiß können mit farbigen Overlays aufgewertet werden. Die Multifunktionsanzeige passt sich der Montageposition des Gerätes an.',
    thirdSlideThird:
      'Die Geräte verfügen über eine Ausgangsleistung von bis zu 2.000 W und besitzen verschiedene elektrische Anschlussmöglichkeiten. Die Heizpatrone VEO ist mit dem einzigartigen Smart-SPLIT-Anschluss ausgestattet.',
    ///
    fourthSlideTitle: 'SMART Sicherheit und Optionen',
    fourthSlideFirst:
      'Die Sicherheit des Benutzers wird durch die Steuerungen mittels Temperaturregelungsalgorithmen gewährleistet, und jedes Heizgerät verfügt über einen eingebauten, speziell ausgewählten Thermoschutz, der eine Überhitzung verhindert. Vordefinierte Schutzfunktionen wie AntiFrost und Fensteröffnungssensor sind permanent im Hintergrund aktiv.',
    fourthSlideSecond:
      'Eine selbstlernende Adaptiv-Start-Funktion und drei Betriebsmodi (Komfort, Ausgewogen und Economy) unterstützen individuelle Benutzerpräferenzen.',
    ///
    appTitle: 'Maßgeschneiderte Applikation',
    appParagraphFrist:
      'Ermöglicht Ihnen die bequeme Verwaltung eines beliebigen Smart-Wi-Fi-Heizgeräts aus der Ferne.',
    appParagraphSecond:
      'Macht die Verwaltung Ihres Hauses einfach, indem es in Zonen unterteilt wird und für jede Zone separate Systemparameter eingestellt werden.',
    appParagraphThird:
      'Bietet messbare wirtschaftliche Vorteile durch die einfache Optimierung des Energieverbrauchs für zum Beheizen Ihres Hauses - mit Hilfe von vorgefertigten Zeitplänen oder einem einfachen Assistenten hilft es, die Zeit- und Temperatureinstellungen des Systems zu optimieren, ohne dabei das Gefühl des hohen thermischen Komforts zu verlieren.',
    appParagraphFourth:
      'Ermöglicht Ihnen die einfache Überwachung der vom System erzeugten Kosten.',
    appParagraphFifth:
      'Kann die Betriebsparameter des Systems flexibel ändern und die Temperatur erhöhen, wenn der Benutzer eine bestimmte Zone im Haus betritt oder sie wieder absenken, wenn er sie verlässt,',
    appParagraphSixth:
      'Ermöglicht die Integration beliebig vieler Heizgeräte und ist damit ideal für die Nutzung als Raumtemperatur-Management-System in Wohnungen und Appartements.',

    productTitleFirst: 'Produkte arbeiten im Smart',
    productTitleSecond: 'System zusammen',
    veoTitle: 'Heizpatrone VEO',
    veoFirst:
      'Die raffinierte Form des Gehäuses und die elegante Frontplatte mit dimmbarem Display verbergen ein scheinbar filigranes Gerät. Die ferngesteuerte Heizpatrone VEO Smart hat eine Leistung von bis zu 2000 W. Dank ihres einzigartigen elektrischen Anschlusses kann sie sowohl vertikal als auch horizontal in praktisch jedem mit einem Heizmedium befüllten Heizkörper installiert werden.',
    veoSecond:
      'Grundlegende Einstellungen (Temperatur und einfacher Timer) sind über die Frontplatte verfügbar, aber der bequemste Zugriff auf die volle Funktionalität des Systems erfolgt über die mobile Anwendung TERMA Smart. Das Gerät arbeitet mit Fensteröffnungssensoren und zusätzlichen Temperatur- und Feuchtigkeitssensoren der SMART-Serie.',

    heatingTitle: 'Thermostatkopf VAZ',
    heatingFirst:
      'Das raffinierte Design der SMART-Familie, das elegante schwarze oder zeitlose weiße Gehäuse sind die charakteristischen Merkmale des VAZ-Thermostatkopfes. Zusammen mit dem dimmbaren Display verleihen sie dem ganzen Gerät eine subtile Raffinesse. Der Kopf wird von einer Hochleistungsbatteriezelle gespeist, die mit einer einzigen Ladung für die gesamte Heizsaison ausreicht.',
    heatingSecond:
      'Durch die extrem einfache Montage und den Selbstkalibrierungsvorgang kann der Kopf in fast jeden Heizkörper und mit jedem Thermostatventiltyp installiert werden. Grundlegende Einstellungen sind über das Bedienfeld auf dem Gerät verfügbar und die volle Funktionalität des Systems wird durch die mobile Anwendung TERMA Smart unterstützt. Das Gerät arbeitet mit "Geöffnete Fenster" Sensoren und zusätzlichen Temperatur- und Feuchtigkeitssensoren der SMART-Serie zusammen.',

    radiatorTitle: 'Heizkörper VOLTAN',
    radiatorFirst:
      'Elektrischer Konvektor VOLTAN - modern, einfach in der Bedienung, effizient und gleichzeitig sehr flach, fast unsichtbar auf der Wand. Der Heizkörper ist mit einem Niedertemperaturtauscher mit einer Leistung von 2000 W und einer fortschrittlichen Steuerung mit einem selbstlernenden Kontrollalgorithmus ausgestattet.',
    radiatorSecond:
      'Grundlegende Regelungen sind über das Bedienfeld auf dem Gerät verfügbar und die volle Funktionalität des Systems wird durch die mobile Anwendung TERMA Smart unterstützt. Das Gerät arbeitet mit "Geöffnete Fenster" Sensoren und zusätzlichen Temperatur- und Feuchtigkeitssensoren der SMART-Serie zusammen.',

    sensorTitle: 'Temperatursonsoren VTS und VWS',
    sensorFirst:
      'Sensoren Temperatursensor und Feuchtigkeitssensor VTS. Der einfach zu montierende Doppelfunktionssensor überwacht permanent Raumtemperatur und Luftfeuchtigkeit. Er sendet Informationen an die Heizgeräte, sobald sich die Temperatur in der kontrollierten Zone nur um ein halbes Grad verändert.',
    sensorSecond:
      'Sensor für "Geöffnetes Fenster" VWS. Sollte ein Fenster geöffnet werden, sendet der Sensor sofort eine Information, wodurch die Heizung in der betreffenden Zone ausgeschaltet wird.',

    available: 'Wir sind 24/7 für Sie erreichbar',
    weWork:
      'Wir arbeiten von Montag bis Freitag von 7:00 bis 18:00 Uhr. Darüber hinaus sind wir 24 Stunden am Tag, 7 Tage die Woche über unsere Mobilfunknummern oder per E-Mail erreichbar.',
    details: 'Firmendaten',
    address: 'Czaple 100 80-298 Gdańsk Polen',
    nip: 'Ust.-Id.-Nr. PL583-10-28-844',
    regon: 'Gewerbenr.: 190558447',
    registration:
      'GIOŚ: E0001379W I Registergericht zu Gdańsk, VIII Wydz. Gosp.',
    KRS: 'REG. Nr. 0000069067',
    capital: 'Stammkapitał:2 360 500 PLN',
    account:
      'Banverbindung: ING Bank Slaski S.A. Oddział w Gdańsku 88 1050 1764 1000 0023 0692 5997',
    form: 'Kontaktformular',
    send: 'Senden',
    terma: 'TERMA GESELLSCHAFT',
    machinery: 'BAUMASCHINEN',
    services: 'INDUSTRIELLE DIENSTLEISTUNGEN',
    galvanizing: 'GALVANIK',
    medical: 'MEDIZINPRODUKTE',
    sale: 'VERTRIEB VON HEIZKÖRPERN',
    //
    thermostatic_head: 'Thermostatkopf',
    temperature_sensor: 'Temperatursensor',
    electric_heater: 'Elektroheizpatrone',
    electric_radiator: 'Elektroheizkörper',
    'window-sensor': 'Offen-Fenster-Sensor',
    buy_sensor: 'Kaufen Sensor',
    buy_termostatic_head: 'Kaufen Thermostatkopf',
    buy_heating_element: 'Kaufen Elektroheizpatrone',
    download: 'Produktkarten',
    VAZ: './product_card/VAZ-v1_DE_20211021_cibto.pdf',
    VTS: './product_card/VTS-v1_DE_20211021_cibto.pdf',
    VOS: './product_card/VOS-v1_DE_20211021_cibto.pdf',
    VEO: './product_card/VEO-v6_EN_20211020_cibto.pdf',
    terma_text: 'TERMA',
    terma_link: 'http://de.termagroup.pl/',
    machinery_text: 'BAUMASCHINEN',
    machinery_link: 'http://www.termamax.pl/de/glowna',
    services_text: ' ',
    services_link: ' ',
    galwanic_text: ' ',
    galwanic_link: ' ',
    medical_text: 'MEDIZINPRODUKTEN',
    medical_link: 'https://www.termamed.pl/de',
  },
  ru: {
    description: 'Описание системы',
    presetation: 'Презентация',
    aboutApp: 'О приложении',
    products: 'Продукция',
    contact: 'Контакт',
    bannerFirst: 'Познакомьтесь с',
    bannerSecond: 'линейкой продуктов WiFi',
    slidTitleFirst: 'Описание системы',
    slidTitleSecond: 'Terma SMART WiFi',
    firstSlideTitle: 'Что такое Terma SMART',
    firstSlideFirst:
      'Это выбор продуктов отопления с дистанционным управлением.',
    firstSlideSecond:
      'Это инновационная система управления отоплением помещения, которую можно легко адаптировать к вашим потребностям, с выбором из трех типов устройств и двух типов датчиков.',
    firstSlideThird:
      'Это система, которая разумно реагирует на изменение условий и коммуникации с помощью облака.',
    ///
    secondSlideTitle: 'Дистанционное управление',
    secondSlideFirst:
      'Уникальной особенностью системы Smart является то, что все устройства напрямую взаимодействуют с локальным (домашним) WiFi - маршрутизатором-таким образом, вам не нужен отдельный модуль управления, и это означает серьезную экономию при покупке системы.',
    secondSlideSecond:
      'Для управления системой используется бесплатное приложение управления Terma Smart, доступное для Android и iOS.',
    ///
    thirdSlideTitle: 'Дизайн и конструкция',
    thirdSlideFirst:
      'Современный дизайн подчеркивает уникальность каждого устройства и поддерживает эргономику работы, в то же время он сочетает в себе все семейство продуктов.',
    thirdSlideSecond:
      'Элегантный черный и неподвластный времени белый цвета могут быть дополнены цветными накладками, а многофункциональные кнопки на панели будут настраиваться в соответствии с положением установки устройства (горизонтальным или вертикальным).',
    thirdSlideThird:
      'Устройства имеют мощность до 2000 w и различные варианты электрических подключений, а электронагреватель VEO оснащен уникальным разъемом Smart SPLIT.',
    ///
    fourthSlideTitle: 'Безопасность и опции SMART',
    fourthSlideFirst:
      'За безопасностью пользователя следят контроллеры, оснащенные алгоритмами контроля температуры, и каждое отопительное оборудование имеет встроенную специально подобранную термозащиту для предотвращения перегрева. В фоновом режиме все время остаются активными предварительно определенные защитные функции, такие как антифриз (замерзание) и датчик открытия окна.',
    fourthSlideSecond:
      'Самообучающаяся функция адаптивного запуска и три режима работы (комфортный, сбалансированный и экономичный) поддерживают индивидуальные предпочтения пользователя.',
    ///
    appTitle: 'Индивидуальное, специальное приложение',
    appParagraphFrist:
      'Это дает удобство удаленного управления каждым электронагревателем Smart Wi-Fi.',
    appParagraphSecond:
      'Oблегчает управление домом за счет разделения на зоны и установки отдельных параметров работы системы для каждой из них.',
    appParagraphThird:
      'Oбеспечивает ощутимые экономические преимущества за счет простой оптимизации энергопотребления для отопления дома - использование готовых графиков или простого планировщика помогает оптимизировать временные и температурные настройки системы без потери теплового комфорта.',
    appParagraphFourth:
      'Позволяет легко контролировать работу устройств по всему дому.',
    appParagraphFifth:
      'Позволяет легко контролировать затраты, генерируемые системой.',
    appParagraphSixth:
      'Mожет гибко изменять рабочие параметры системы и повышать температуру, когда пользователь входит в определенную зону в доме, или снова опускать ее, когда он покидает ее.',
    appParagraphSeventh:
      'Позволяет интегрировать любое количество отопительных приборов, что делает его идеальным в качестве системы управления комнатной температурой в квартирах и аппартаментах.',

    productTitleFirst: 'Продукты SMART',
    productTitleSecond: '',
    veoTitle: 'Электронагреватель VEO',
    veoFirst:
      'За сложной формой корпуса и элегантной передней панелью имеющей затемнённый дисплей скрывается, казалось бы, хрупкое устройство. Фактически, дистанционно управляемый электронагреватель VEO Smart имеет мощность до 2000 w, а уникальное электрическое соединение позволяет устанавливать его как вертикально, так и горизонтально, практически в каждом радиаторе с теплоносителем.',
    veoSecond:
      'Основные настройки (температура и простой таймер) доступны через переднюю панель, но наиболее удобный доступ к полному функционалу системы обеспечивает мобильное приложение TERMA Smart. Устройство работает с датчиками открывания окон и дополнительным датчиком температуры и влажности из серии SMART.',

    heatingTitle: 'Термоголовка VAZ',
    heatingFirst:
      'Изысканный дизайн семейства SMART, элегантный черный или неподвластный времени белый корпус являются отличительными чертами термостатической головки VAZ. Вместе с заттемняющимся дисплеем они добавляют тонкости всему устройству. Головка питается от высокопроизводительного аккумуляторного элемента, которая заряжается одним зарядом в течение всего отопительного сезона.',
    heatingSecond:
      'Чрезвычайно простая сборка и процедура автоматической калибровки позволяют устанавливать головку практически в любой радиатор и с любым типом термостатического клапана. Основные правила доступны через панель на устройстве, а полная функциональность системы поддерживается мобильным приложением TERMA Smart. Устройство работает с датчиками открывания окон и дополнительным датчиком температуры и влажности из серии SMART.',

    radiatorTitle: 'Радиатор VOLTAN',
    radiatorFirst:
      'Электрический конвектор VOLTAN-современный, простой в использовании, эффективный, но очень плоский, почти не различимый на фоне стены. Нагреватель оснащен низкотемпературным теплообменником мощностью 2000w и усовершенствованным контроллером с самообучающимся алгоритмом управления.',
    radiatorSecond:
      'Основные настройки доступны через панель на устройстве, а полную функциональность системы поддерживает мобильное приложение Terma Smart. Устройство работает с датчиками открытия окна и дополнительным датчиком температуры и влажности серии SMART.',

    sensorTitle: 'Датчики VTS и VWS',
    sensorFirst:
      'Датчик температуры и влажности VTS. Простой в установке двухфункциональный датчик постоянно контролирует температуру и влажность в помещении, отправляя информацию в отопительные приборы, как только температура в контролируемой зоне изменяется на полградуса. ',
    sensorSecond:
      'VWS датчик открытого окна. Когда окно открывается, датчик немедленно отправляет информацию об отключении обогрева в данной зоне.',

    available: 'Мы доступны 24/7',
    weWork:
      'Работаем с понедельника по пятницу с 07:00 до 18:00. Кроме того, мы доступны 24 часа в сутки, 7 дней в неделю, используя номера мобильных телефонов и электронную почту.',
    details: 'Данные компании',
    address: 'Czaple 100 80-298 Гданьск Польша',
    nip: 'NIP:583-10-18-844',
    regon: 'REGON: 190558447',
    registration:
      'Рег. № GIOŚ: E0001379W I Sąd Rej. w Gdańsku, VIII Wydz. Gosp.',
    KRS: 'KRS № 0000069067',
    capital: 'Капитал: 2 360 500 PLN',
    account:
      'Номер банковского счета: ING Bank Slaski S.A. Филиал в Гданьске 88 1050 1764 1000 0023 0692 5997 ',
    form: 'Форма обратной связи',
    send: 'Отправить',
    terma: 'TERMA',
    machinery: 'СТРОИТЕЛЬНАЯ ТЕХНИКА',
    services: 'ПРОМЫШЛЕННЫЕ УСЛУГИ',
    galvanizing: 'ГАЛЬВАНИЗАЦИЯ',
    medical: 'МЕДИЦИНСКИЕ ИЗДЕЛИЯ',
    sale: 'ПРОДАЖА РАДИАТОРОВ',

    thermostatic_head: 'Термостатическая головка',
    temperature_sensor: 'Датчик температуры',
    electric_heater: 'Электронагреватель',
    electric_radiator: 'Электрический радиатор',
    'window-sensor': 'Датчик открытия окна',
    buy_sensor: 'Купить датчик',
    buy_termostatic_head: 'Купить термостатическую головку',
    buy_heating_element: 'Купить электронагреватель',
    download: 'Техническая карта',
    VAZ: './product_card/VAZ-v1_EN_20211021_cibto.pdf',
    VTS: './product_card/VTS-v1_RU_20211022_cibto.pdf',
    VOS: './product_card/VOS-v1_RU_20211022_cibto.pdf',
    VEO: './product_card/VEO-v6_EN_20211020_cibto.pdf',
    terma_text: 'TERMA',
    terma_link: 'http://ru.termagroup.pl/',
    machinery_text: 'СТРОИТЕЛЬНЫЕ МАШИНЫ',
    machinery_link: 'http://www.termamax.pl/ru/glowna',
    services_text: ' ',
    services_link: ' ',
    galwanic_text: ' ',
    galwanic_link: ' ',
    medical_text: 'МЕДЕЦИНСКИЕ ИЗДЕЛИЯ',
    medical_link: 'https://www.termamed.pl/en',
  },
  pl: {
    description: 'Opis systemu',
    presetation: 'Prezentacja',
    aboutApp: 'O aplikacji',
    products: 'Produkty',
    contact: 'Kontakt',
    bannerFirst: 'Poznaj rodzinę naszych',
    bannerSecond: 'produktów WiFi',
    slidTitleFirst: 'Opis systemu',
    slidTitleSecond: 'Terma SMART WiFi',
    firstSlideTitle: 'Czym jest Terma SMART',
    firstSlideFirst:
      'To gama elektrycznych produktów grzewczych sterowanych bezprzewodowo.',
    firstSlideSecond:
      'To innowacyjnie zaprojektowany system sterowania ogrzewaniem pomieszczeń, który dopasujesz z łatwością do swoich potrzeb, mając do wyboru trzy typy urządzeń i dwa rodzaje czujników.',
    firstSlideThird:
      'To system inteligentnie reagujący na zmieniające się warunki i komunikacja z wykorzystaniem chmury.',
    ///
    secondSlideTitle: 'Zdalne sterowanie',
    secondSlideFirst:
      'Unikalną cechą systemu Smart jest to, że wszystkie urządzenia komunikują się bezpośrednio z lokalnym (domowym) routerem wifi - dzięki temu nie jest potrzebny żaden oddzielny moduł kontrolny, a to oznacza poważną oszczędność przy zakupie systemu.',
    secondSlideSecond:
      'Do zarządzania systemem służy darmowa aplikacja sterująca TERMA Smart, dostępna dla systemów Android oraz iOS. ',
    ///
    thirdSlideTitle: 'Design i konstrukcja',
    thirdSlideFirst:
      'Nowoczesny design podkreśla unikalność każdego z urządzeń wspierając ergonomię użytkowania, a jednocześnie spaja całą rodzinę produktów.',
    thirdSlideSecond:
      'Elegancką czerń i ponadczasową biel można wzbogacić kolorowymi nakładkami, a wielofunkcyjny wskaźnik dostosuje się do pozycji montażu urządzenia.',
    thirdSlideThird:
      'Urządzenia dysponują mocą do 2 000W i różnymi wariantami przyłączy elektrycznych, a grzałka VEO wyposażona jest w unikalne złącze Smart SPLIT.',
    ///
    fourthSlideTitle: 'Bezpieczeństwo i opcje SMART',
    fourthSlideFirst:
      'Nad bezpieczeństwem użytkownika czuwają sterowniki wyposażone w algorytmy kontrolujące temperaturę, a każde z urządzeń grzewczych posiada wbudowane specjalnie dobrane zabezpieczenie termiczne, zapobiegające przegrzaniu. W tle cały czas pozostają aktywne zdefiniowane wstępnie funkcje ochronne, jak AntiFrost oraz czujnik otwarcia okna.',
    fourthSlideSecond:
      'Samoucząca się funkcja Wcześniejszy Start oraz trzy tryby pracy (Komfortowy, Zbalansowany i Ekonomiczny) wspierają indywidualne preferencje użytkownika.',
    ///
    appTitle: 'Aplikacja uszyta na miarę',
    appParagraphFrist:
      'Daje komfort zdalnego zarządzania każdym urządzeniem grzewczym Smart wi-fi.',
    appParagraphSecond:
      'Ułatwia zarządzanie domem poprzez podział na strefy i ustalanie dla każdej z nich odrębnych parametrów pracy systemu.',
    appParagraphThird:
      'Dostarcza wymiernych korzyści ekonomicznych poprzez łatwą optymalizację zużycia energii na ogrzewanie domu – korzystając z gotowych harmonogramów lub z prostego kreatora pomaga zoptymalizować ustawienia czasu i temperatury pracy systemu, nie tracąc poczucia wysokiego komfortu cieplnego.',
    appParagraphFourth:
      'Pozwala łatwo monitorować pracę urządzeń w całym domu.',
    appParagraphFifth:
      'Pozwala łatwo monitorować koszty generowane przez system.',
    appParagraphSixth:
      'Może elastycznie modyfikować parametry pracy systemu podwyższając temperaturę kiedy Użytkownik wkracza w określoną strefę wokół domu lub obniżając, kiedy ją opuszcza.',
    appParagraphSeventh:
      'Pozwala zintegrować dowolną ilość urządzeń grzewczych, dzięki czemu doskonale sprawdzi się jako system zarządzania temperaturą pomieszczeń w mieszkaniach i apartamentach.',
    ///
    productTitleFirst: 'Produkty współpracujące',
    productTitleSecond: 'w systemie Smart',
    veoTitle: 'Grzałka VEO',
    veoFirst:
      'Grzałka VEO Wyrafinowany kształt obudowy i elegancki panel frontowy z przygasającym wyświetlaczem kryją w sobie delikatne z pozoru urządzenie. W rzeczywistości zdalnie sterowana grzałka VEO Smart dysponuje mocą do 2000 W, a unikalne przyłącze elektryczne pozwala zainstalować ją zarówno w pionie, jak i w poziomie, praktycznie w każdym grzejniku z czynnikiem grzewczym.',
    veoSecond:
      'Podstawowe regulacje (temperatura i prosty Timer) dostępne są poprzez panel frontowy, ale najwygodniejszy dostęp do pełnej funkcjonalności systemu daje aplikacja mobilna TERMA Smart. Urządzenie współpracuje z czujnikami otwarcia okna oraz dodatkowym czujnikiem temperatury i wilgotności serii SMART.',

    heatingTitle: 'Głowica VAZ',
    heatingFirst:
      'Wyrafinowane wzornictwo rodziny SMART, elegancka czerń lub ponadczasowa biel obudowy to cechy charakterystyczne głowicy termostatycznej VAZ. Razem przygasającym wyświetlaczem nadają subtelności całemu urządzeniu. Głowica zasilana jest wysokowydajnym ogniwem akumulatorowym, którego pojedyncze ładowanie wystarcza na cały sezon grzewczy.',
    heatingSecond:
      'Niezwykle łatwy montaż oraz procedura autokalibracji pozwalają na instalację głowicy niemal w każdym grzejniku i z każdym typem zaworu termostatycznego. Podstawowe regulacje dostępne są poprzez panel na urządzeniu, a pełną funkcjonalność systemu obsługuje aplikacja mobilna TERMA Smart. Urządzenie współpracuje z czujnikami otwarcia okna oraz dodatkowym czujnikiem temperatury i wilgotności serii SMART.',

    radiatorTitle: 'Grzejnik VOLTAN',
    radiatorFirst:
      'Elektryczny konwektor VOLTAN - nowoczesny, prosty w obsłudze, wydajny, a jednocześnie bardzo płaski, niemal niewyróżniający się na tle ściany. Grzejnik wyposażony jest w niskotemperaturowy wymiennik o mocy 2000 W i zaawansowany sterownik z samouczącym się algorytmem kontrolnym.',
    radiatorSecond:
      'Podstawowe regulacje dostępne są poprzez panel na urządzeniu, a pełną funkcjonalność systemu obsługuje aplikacja mobilna TERMA Smart. Urządzenie współpracuje z czujnikami otwarcia okna oraz dodatkowym czujnikiem temperatury i wilgotności serii SMART.',

    sensorTitle: 'Czujniki VTS i VWS',
    sensorFirst:
      'Czujniki Czujnik temperatury i wilgotności VTS. Łatwy w montażu dwufunkcyjny czujnik stale monitoruje temperaturę i wilgotność w pomieszczeniu, wysyłając informacje do urządzeń grzewczych, jeśli tylko temperatura w kontrolowanej strefie zmieni się o pół stopnia.',
    sensorSecond:
      'Czujnik otwarcia okna VWS. W przypadku otwarcia okna czujnik natychmiast wysyła informację powodującą wyłączenie ogrzewania w danej strefie.',

    available: 'Jesteśmy dostępni 24/7',
    weWork:
      'Pracujemy od poniedziałku do piątku od 07:00 do 18:00. Ponadto jesteśmy dostępni 24 h na dobę przez 7 dni w tygodniu pod numerami telefonów komórkowych oraz za pośrednictwem poczty e-mail.',
    details: 'Dane firmy',
    address: 'Czaple 100 80-298 Gdańsk Polska',
    nip: 'NIP:583-10-18-844',
    regon: 'REGON: 190558447',
    registration:
      'nr rej. GIOŚ: E0001379W I Sąd Rej. w Gdańsku, VIII Wydz. Gosp.',
    KRS: 'KRS nr 0000069067',
    capital: 'Kapitał:2 360 500PLN',
    account:
      'Nr konta bankowego: ING Bank Slaski S.A. Oddział w Gdańsku 88 1050 1764 1000 0023 0692 5997',
    form: 'Formularz kontaktowy',
    send: 'Wyślij',
    terma: 'TERMA SPÓŁKA',
    machinery: 'MASZYNY BUDOWLANE',
    services: 'USŁUGI PRZEMYSŁOWE',
    galvanizing: 'GALWANIZERNIA',
    medical: 'PRODUKTY MEDYCZNE',
    sale: 'WYPRZEDAŻ GRZEJNIKÓW',
    //
    thermostatic_head: 'Głowica termostatyczna',
    temperature_sensor: 'Czujnik temperatury',
    electric_heater: 'Grzalka elektryczna',
    electric_radiator: 'Grzejnik elektryczny',
    'window-sensor': 'Czujnik otwarcia okna',
    buy_sensor: 'Kup czujnik',
    buy_radiator: 'Kup głowice',
    buy_heating_element: 'Kup grzałkę',
    download: 'Karta techniczna',
    VAZ: './product_card/VAZ-v1_PL_20211021_cibto.pdf',
    VTS: './product_card/VTS-v1_PL_20211021_cibto.pdf',
    VOS: './product_card/VOS-v1_PL_20211021_cibto.pdf',
    VEO: './product_card/VEO-v6_PL_20211020_cibto.pdf',
    terma_text: 'TERMA SPÓŁKA',
    terma_link: 'http://www.termagroup.pl/',
    machinery_text: 'MASZYNY BUDOWLANE',
    machinery_link: 'http://www.termamax.pl/pl/glowna',
    services_text: 'USŁUGI PRZEMYSŁOWE',
    services_link: 'http://www.termaservices.pl/',
    galwanic_text: 'GALWANIZERNIA',
    galwanic_link: 'http://www.termagalvanic.pl/',
    medical_text: 'PRODUKTY MEDYCZNE',
    medical_link: 'https://www.termamed.pl/',
  },
  fr: {
    description: 'Description',
    presetation: 'Présentation',
    aboutApp: "À propos de l'application",
    products: 'Des Produits',
    contact: 'Contactez nous',
    bannerFirst: 'Découvrez les produits',
    bannerSecond: 'du système WiFi Terma',
    slidTitleFirst: 'Description du système',
    slidTitleSecond: 'Terma SMART WiFi',
    firstSlideTitle: "Qu'est-ce que Terma SMART",
    firstSlideFirst:
      "С'est une gamme de produits de chauffage électrique à commande sans fil.",
    firstSlideSecond:
      "Il s'agit d'un système de régulation de chauffage au design innovant qui peut être facilement adapté à vos besoins, comprenant un choix de trois types d'appareils et deux types de capteurs.",
    firstSlideThird:
      "C'est un système qui répond intelligemment aux conditions changeantes et communique via le cloud.",
    ///
    secondSlideTitle: 'Télécommande',
    secondSlideFirst:
      "Une caractéristique unique du système Smart est que tous les appareils communiquent directement avec le routeur wifi local (domestique) - aucun module de contrôle séparé n'est donc nécessaire, ce qui signifie une économie importante lors de l'achat du système.",
    secondSlideSecond:
      "Le système est géré par l'application gratuite TERMA Smart control, disponible pour Android et iOS.",
    ///
    thirdSlideTitle: 'Conception et réalisation',
    thirdSlideFirst:
      "Le design moderne met l'accent sur le caractère unique de chaque appareil, prend en charge l'ergonomie d'utilisation et lie toute la famille de produits.",
    thirdSlideSecond:
      "Le noir élégant et le blanc intemporel peuvent être enrichis de plaques de recouvrement colorées, et les boutons du panneau multifonctions s'adapteront à la position de montage de l'appareil (horizontale ou verticale).",
    thirdSlideThird:
      "La puissance de sortie des appareils va jusqu'à 2 000 W, comporte quelques variantes de connexions électriques et l'élément chauffant VEO est équipé d'un connecteur Smart SPLIT unique.",
    ///
    fourthSlideTitle: 'Options de sécurité et SMART',
    fourthSlideFirst:
      "La sécurité de l'utilisateur est assurée par des contrôleurs équipés d'algorithmes de contrôle de température, et chaque appareil de chauffage dispose d'une protection thermique spécialement sélectionnée pour éviter la surchauffe. Les fonctions de protection prédéfinies telles que l'Antigel et le détecteur d'ouverture de fenêtre restent actives en arrière-plan.",
    fourthSlideSecond:
      "La fonction d'auto-apprentissage Adaptiv Start et les trois modes de fonctionnement (Confort, Équilibre et Économique) prennent en charge les préférences individuelles de l'utilisateur.",
    ///
    appTitle: 'Application dédiée',
    appParagraphFrist:
      'Donne le confort de la gestion à distance de chaque appareil de chauffage Smart wi-fi.',
    appParagraphSecond:
      "Facilite la gestion du chauffage domestique en divisant la maison en zones et en définissant des paramètres de fonctionnement du système distincts pour chacune d'entre elles.",
    appParagraphThird:
      "Offre des avantages économiques tangibles en optimisant facilement la consommation d'énergie pour le chauffage de la maison - l'utilisation de programmes prêts ou d'un simple programmateur permet d'optimiser les réglages de temps et de température du système sans perdre le confort thermique.",
    appParagraphFourth:
      'Vous permet de surveiller facilement le fonctionnement des appareils dans toute la maison.',
    appParagraphFifth:
      'Permet de suivre facilement les coûts générés par le système.',
    appParagraphSixth:
      "Permet une modification flexible des paramètres de fonctionnement du système en augmentant la température lorsque l'utilisateur entre dans une zone spécifique ou en l'abaissant lorsqu'il est absent.",
    appParagraphSeventh:
      "Vous permet d'intégrer un nombre illimité d'appareils de chauffage, ce qui le rend parfait comme système de gestion de la température ambiante dans les appartements et les appartements.",

    productTitleFirst: 'Les produits',
    productTitleSecond: 'du système SMART',
    veoTitle: 'Élément chauffant VEO',
    veoFirst:
      "Chauffage VEO La forme sophistiquée du boîtier et un panneau avant élégant avec un écran décoloré dissimulent un appareil apparemment délicat. En fait, l'élément chauffant VEO Smart télécommandé a une puissance allant jusqu'à 2000 W, et la connexion électrique unique lui permet d'être installé à la fois verticalement et horizontalement, presque dans n'importe quel radiateur avec un fluide de chauffage.",
    veoSecond:
      "Réglages de base (température et un simple minuterie) sont disponibles via le panneau avant, mais l'accès le plus pratique à toutes les fonctionnalités du système est fourni par l'application mobile TERMA Smart. L'appareil fonctionne avec des capteurs d'ouverture de fenêtre et un capteur de température et d'humidité supplémentaire de la série SMART.",

    heatingTitle: 'Tête thermostatique VAZ',
    heatingFirst:
      "Le design sophistiqué de la famille SMART, le noir élégant ou le blanc intemporel du boîtier sont les maîtres mots de la tête thermostatique VAZ. Associés à l'affichage décoloré, ils ajoutent de la subtilité à l'ensemble de l'appareil. La tête est alimentée par un cellule de batterie, qui est chargée sur une seule charge pendant toute la saison de chauffage.L'assemblage facile et la prcédure d'auto-étalonnage permettent d'installer la tête dans la majorité des vannes thermostatiques.",
    heatingSecond:
      "L'assemblage extrêmement facile et la procédure d'auto-étalonnage permettent d'installer la tête dans presque tous les radiateurs et avec n'importe quel type de vanne thermostatique. Les réglementations de base sont disponibles via le panneau de l'appareil et toutes les fonctionnalités du système sont prises en charge par l'application mobile TERMA Smart. L'appareil fonctionne avec des capteurs d'ouverture de fenêtre et un capteur de température et d'humidité supplémentaire de la série SMART.",

    radiatorTitle: 'Radiateur VOLTAN',
    radiatorFirst:
      "Convecteur électrique VOLTAN - moderne, facile à utiliser, efficace et en même temps très plat, presque indiscernable sur le fond du mur. Le radiateur est équipé d'un échangeur de chaleur à basse température de 2000 W et d'un contrôleur avancé avec un -apprentissage de l'algorithme de contrôle.",
    radiatorSecond:
      "Les paramètres de base sont disponibles via le panneau l'appareil et toutes les fonctionnalités du système sont prises en charge par l'application du mobile TERMA Smart, L'appareil fonctionne avec des capteurs d'ouverture de fenêtre et un capteur de température d'humidité dans la série Smart.",

    sensorTitle: 'Capteurs',
    sensorFirst:
      "Capteur de température et d'humidité VTS. Le capteur a une double fonction facile à installer , il surveille en permanence la tempèrature et l'humiditéde la pièce et envoie des informations aux appareils de chauffage dès que la température dans la zone change d'un demi-degré.",
    sensorSecond:
      "Capteur de fenêtre ouverte VWS. Al'ouverture de la fenêtre, la sonde envoie immédiatement une information pour éteindre le chauffage dans la zone donnée.",

    available: 'Nous sommes disponibles 24/7',
    weWork:
      "Nous travaillons du lundi au vendredi de 07h00 à 18h00. De plus, nous sommes disponibles 24 heures sur 24, 7 jours sur 7, à l'aide de numéros de téléphone portable et par e-mail.",
    details: "Détails de l'entreprise",
    address: 'Czaple 100 80-298 Gdańsk Pologne',
    nip: 'NIP:583-10-18-844',
    regon: 'REGON: 190558447',
    registration:
      'Enregistrement de la société: E0001379W I Sąd Rej. w Gdańsku, VIII Wydz. Gosp.',
    KRS: 'KRS № 0000069067',
    capital: 'Capital: 2 360 500 PLN',
    account:
      'Nr Konta Bankowego: ING Bank Slaski S.A. Oddzial w Gdansku 88 1050 1764 1000 0023 0692 5997 ',
    form: 'Formulaire de contact',
    send: 'Envoyer',
    terma: 'TERMA',
    machinery: 'MACHINES DE CONSTRUCTION',
    services: 'SERVICES INDUSTRIELS',
    galvanizing: 'GALVANISATION',
    medical: 'MATERIELS MEDICAUX',
    sale: 'VENTE DE RADIATEURS',
    //
    thermostatic_head: 'Tête thermostatique',
    temperature_sensor: 'Capteur de température',
    electric_heater: 'Kit résistances électrique',
    electric_radiator: 'Radiateur électrique',
    'window-sensor': "Capteur d'ouverture de fenêtre",
    buy_sensor: 'Buy sensor',
    buy_termostatic_head: 'Buy thermostatic head',
    buy_heating_element: 'Buy heating element',
    download: 'Product card',
    VAZ: './product_card/VAZ-v1_EN_20211021_cibto.pdf',
    VTS: './product_card/VTS-v1_FR_20211025_cibto.pdf',
    VOS: './product_card/VOS-v1_FR_20211025_cibto.pdf',
    VEO: './product_card/VEO-v6_EN_20211020_cibto.pdf',
    terma_text: 'TERMA',
    terma_link: 'http://en.termagroup.pl/',
    machinery_text: 'MACHINERY',
    machinery_link: 'http://www.termamax.pl/en/glowna',
    services_text: ' ',
    services_link: ' ',
    galwanic_text: ' ',
    galwanic_link: ' ',
    medical_text: 'MEDICAL PRODUCTS',
    medical_link: 'https://www.termamed.pl/en',
  },
  it: {
    description: 'Descrizione',
    presetation: 'Presentazione',
    aboutApp: "Informazioni sull'app",
    products: 'Prodotti',
    contact: 'Contattaci',
    bannerFirst: 'Incontra la nostra',
    bannerSecond: 'famiglia prodotti WiFi',
    slidTitleFirst: 'Descrizione del sistema',
    slidTitleSecond: 'Terma SMART WiFi',
    firstSlideTitle: "Cos'è Terma SMART",
    firstSlideFirst:
      'È una gamma di prodotti per il riscaldamento elettrico controllati in modalità wireless.',
    firstSlideSecond:
      'È un sistema di controllo del riscaldamento dal design innovativo che può essere facilmnte adattato alle tue esigenze, che include una scelta di tre tipi di dispositivi e due tipi di sensori.',
    firstSlideThird:
      'È un sistema che risponde in modo intelligente alle condizioni mutevoli e comunica tramite il cloud.',
    ///
    secondSlideTitle: 'Telecomando',
    secondSlideFirst:
      "Una caratteristica unica del sistema Smart è che tutti i dispositivi comunicano direttamente con il router wifi locale (domestico), quindi non è necessario alcun modulo di controllo separato, il che significa un notevole risparmio nell'acquisto del sistema.",
    secondSlideSecond:
      "Il sistema è gestito dall'app gratuita TERMA Smart control, disponibile per Android e iOS.",
    ///
    thirdSlideTitle: 'Progettazione e costruzione',
    thirdSlideFirst:
      "Il design moderno enfatizza l'unicità di ogni dispositivo, supporta l'ergonomia di utilizzo e lega l'intera famiglia di prodotti.",
    thirdSlideSecond:
      "L'elegante nero e l'intramontabile bianco possono essere arricchiti con placche colorate e i pulsanti del pannello multifunzione si adatteranno alla posizione di montaggio del dispositivo (orizzontale o verticale).",
    thirdSlideThird:
      "La potenza in uscita dei dispositivi arriva fino a 2.000 W, presenta alcune varianti di collegamenti elettrici e l'elemento riscaldante VEO è dotato di un connettore Smart SPLIT unico.",
    ///
    fourthSlideTitle: 'Sicurezza e opzioni SMART',
    fourthSlideFirst:
      "La sicurezza dell'utente è garantita da controllori dotati di algoritmi di controllo della temperatura e ogni dispositivo di riscaldamento ha una protezione termica appositamente selezionata per evitare il surriscaldamento. Le funzioni di protezione predefinite come Antigelo e il rilevatore di apertura finestra rimangono attive in background.",
    fourthSlideSecond:
      "La funzione Adaptiv Start ad autoapprendimento e le tre modalità operative (Comfort, Balance ed Economic) supportano le preferenze individuali dell'utente.",
    ///
    appTitle: 'App dedicata',
    appParagraphFrist:
      'Offre la comodità della gestione remota di ogni dispositivo di riscaldamento smart wi-fi.',
    appParagraphSecond:
      "Facilita la gestione del riscaldamento domestico suddividendo la casa in zone e impostando parametri di funzionamento dell'impianto separati per ciascuna di esse.",
    appParagraphThird:
      "Offre vantaggi economici tangibili ottimizzando facilmente i consumi energetici per il riscaldamento della casa - l'utilizzo di orari prestabiliti o di un semplice programmatore orario aiuta ad ottimizzare le impostazioni di tempo e temperatura dell'impianto senza perdere il comfort termico.",
    appParagraphFourth:
      'Consente di monitorare facilmente il funzionamento dei dispositivi in ​​tutta la casa.',
    appParagraphFifth:
      'Permette di monitorare facilmente i costi generati dal sistema.',
    appParagraphSixth:
      "Consente la modifica flessibile dei parametri di funzionamento del sistema aumentando la temperatura quando l'Utente entra in una zona specifica o abbassandola quando si allontana.",
    appParagraphSeventh:
      'Permette di integrare qualsiasi numero di dispositivi di riscaldamento, rendendolo perfetto come sistema di gestione della temperatura ambiente in appartamenti e bilocali.',

    productTitleFirst: 'I prodotti del',
    productTitleSecond: 'sistema SMART',
    veoTitle: 'Elemento riscaldante VEO',
    veoFirst:
      "Riscaldatore VEO La forma sofisticata dell'alloggiamento e un elegante pannello frontale con display sbiadito nascondono un dispositivo apparentemente delicato. Infatti, l'elemento riscaldante VEO Smart comandato a distanza ha una potenza fino a 2000 W e l'esclusivo collegamento elettrico ne consente l'installazione sia in verticale che in orizzontale, quasi in qualsiasi radiatore dotato di mezzo riscaldante.",
    veoSecond:
      "Regolazioni di base (temperatura e semplice timer) sono disponibili tramite il pannello frontale, ma l'accesso più comodo alla piena funzionalità del sistema è fornito dall'applicazione mobile TERMA Smart. Il dispositivo funziona con sensori di apertura finestra e un sensore aggiuntivo di temperatura e umidità della serie SMART.",

    heatingTitle: 'Testa termostatica VAZ',
    heatingFirst:
      "Il design sofisticato della famiglia SMART, l'elegante nero o l'intramontabile bianco dell'alloggiamento sono i tratti distintivi della testa termostatica VAZ. Insieme al display sbiadito, aggiungono sottigliezza all'intero dispositivo. La testa è alimentata da una cella di batteria ad alte prestazioni, che viene caricata con una singola carica per l'intera stagione di riscaldamento.",
    heatingSecond:
      "L'estrema facilità di montaggio e la procedura di autotaratura consentono di installare la testata in quasi tutti i radiatori e con qualsiasi tipo di valvola termostatica. Le normative di base sono disponibili tramite il pannello sul dispositivo e la piena funzionalità del sistema è supportata dall'applicazione mobile TERMA Smart. Il dispositivo funziona con sensori di apertura finestra e un sensore aggiuntivo di temperatura e umidità della serie SMART.",

    radiatorTitle: 'Termosifone VOLTAN',
    radiatorFirst:
      'Termoconvettore elettrico VOLTAN - moderno, facile da usare, efficiente e allo stesso tempo molto piatto, quasi indistinguibile sullo sfondo del muro. Il riscaldatore è dotato di uno scambiatore di calore da 2000 W a bassa temperatura e di un controller avanzato con un algoritmo di controllo ad autoapprendimento.',
    radiatorSecond:
      "Le impostazioni di base sono disponibili tramite il pannello sul dispositivo e la piena funzionalità del sistema è supportata dall'applicazione mobile TERMA Smart. Il dispositivo funziona con sensori di apertura finestra e un sensore aggiuntivo di temperatura e umidità della serie SMART.",

    sensorTitle: 'Sensors VTS et VWS',
    sensorFirst:
      "Sensore di temperatura e umidità VTS. Un sensore a doppia funzione di facile installazione monitora costantemente la temperatura e l'umidità nell'ambiente, inviando informazioni ai dispositivi di riscaldamento non appena la temperatura nella zona controllata cambia di mezzo grado.",
    sensorSecond:
      "Sensore finestra aperta VWS. All'apertura della finestra, il sensore invia immediatamente le informazioni per spegnere il riscaldamento in una determinata zona.",

    available: 'Siamo disponibili 24 ore su 24, 7 giorni su 7',
    weWork:
      'Lavoriamo dal lunedì al venerdì dalle 07:00 alle 18:00. Inoltre, siamo disponibili 24 ore su 24, 7 giorni su 7, utilizzando i numeri di cellulare e via e-mail.',
    details: 'Dettagli della Compagnia',
    address: 'Czaple 100 80-298 Gdańsk Poland',
    nip: 'NIP:583-10-18-844',
    regon: 'REGON: 190558447',
    registration:
      'Company registration: E0001379W I Sąd Rej. w Gdańsku, VIII Wydz. Gosp.',
    KRS: 'KRS № 0000069067',
    capital: 'Capital: 2 360 500 PLN',
    account:
      'Nr konta bankowego: ING Bank Slaski S.A. Oddział w Gdańsku 88 1050 1764 1000 0023 0692 5997 ',
    form: 'Modulo di Contatto',
    send: 'Inviare',
    terma: 'TERMA',
    machinery: 'MACCHINE DA CANTIERE',
    services: 'SERVIZI INDUSTRIALI',
    galvanizing: 'ZINCATURA',
    medical: 'PRODOTTI MEDICI',
    sale: 'VENDITA RADIATORI',
    //
    thermostatic_head: 'Testa termostatica',
    temperature_sensor: 'Termometro',
    electric_heater: 'Kit riscaldatore elettrico',
    electric_radiator: 'Stufa elettrica',
    'window-sensor': 'Sensore di apertura della finestra',
    buy_sensor: 'Buy sensor',
    buy_termostatic_head: 'Buy thermostatic head',
    buy_heating_element: 'Buy heating element',
    download: 'Product card',
    VAZ: './product_card/VAZ-v1_EN_20211021_cibto.pdf',
    VTS: './product_card/VTS-v1_EN_20211021_cibto.pdf',
    VOS: './product_card/VOS-v1_EN_20211021_cibto.pdf',
    VEO: './product_card/VEO-v6_EN_20211020_cibto.pdf',
    terma_text: 'TERMA',
    terma_link: 'http://en.termagroup.pl/',
    machinery_text: 'MACHINERY',
    machinery_link: 'http://www.termamax.pl/en/glowna',
    services_text: ' ',
    services_link: ' ',
    galwanic_text: ' ',
    galwanic_link: ' ',
    medical_text: 'MEDICAL PRODUCTS',
    medical_link: 'https://www.termamed.pl/en',
  },
  cs: {
    description: 'Popis systému',
    presetation: 'Prezentace',
    aboutApp: 'O aplikaci',
    products: 'Produkty',
    contact: 'Kontakt',
    bannerFirst: 'Seznam se s rodinou',
    bannerSecond: 'našich produktů Wifi',
    slidTitleFirst: 'Popis systému',
    slidTitleSecond: 'Terma SMART WiFi',
    firstSlideTitle: 'Co je Terma SMART',
    firstSlideFirst: 'Linie elektrických produktů řízených bezdrátově.',
    firstSlideSecond:
      'Je inovativně navržený řídicí systém vytápění místnosti, který lze snadno přizpůsobit vašim potřebám, s výběrem ze tří typů zařízení a dvou typů čidel.',
    firstSlideThird:
      'Je systém, který inteligentně reaguje na měnící se podmínky a komunikaci pomocí cloudu.',
    ///
    secondSlideTitle: 'Dálkové ovládání',
    secondSlideFirst:
      'Jedinečnou vlastností systému Smart je, že všechna zařízení komunikují přímo s místním (domácím) routerem wifi - není tedy potřeba žádný samostatný řídicí centrální modul, což znamená výraznou úsporu při nákupu systému.',
    secondSlideSecond:
      'Systém je řízen bezplatnou ovládací aplikací TERMA Smart, která je k dispozici pro Android a iOS.',
    ///
    thirdSlideTitle: 'Design a konstrukce',
    thirdSlideFirst:
      'Moderní design zdůrazňuje jedinečnost každého zařízení, podporuje ergonomii užívání a zároveň spojuje celou rodinu produktů.',
    thirdSlideSecond:
      'Elegantní černou a nadčasovou bílou lze obohatit barevnými okraji a multifunkční indikátor teploty se přizpůsobí montážní poloze zařízení.',
    thirdSlideThird:
      'Zařízení mají výkon až 2 000 W a různé varianty elektrického připojení a topná tyč VEO je vybavena jedinečným konektorem Smart SPLIT.',
    ///
    fourthSlideTitle: 'Bezpečnost a možnosti SMART',
    fourthSlideFirst:
      'Bezpečnost uživatele zajišťují regulátory vybavené algoritmy řízení teploty a každé topné zařízení má speciálně zvolenou tepelnou ochranu, aby se zabránilo přehřátí. Předdefinované ochranné funkce, jako je AntiFrost a detektor otevírání oken, zůstávají aktivní na pozadí.',
    fourthSlideSecond:
      'Samoučící se funkce Early Start a tři provozní režimy (komfortní, normální a ekonomický) podporují individuální preference uživatele.',
    ///
    appTitle: 'Aplikace na míru',
    appParagraphFrist:
      'Poskytuje pohodlí vzdálené správy každého inteligentního wi-fi topného zařízení.',
    appParagraphSecond:
      'Usnadňuje správu domů rozdělením do zón a nastavením samostatných provozních parametrů systému pro každou z nich.',
    appParagraphThird:
      'Poskytuje hmatatelné ekonomické výhody díky snadné optimalizaci spotřeby energie na vytápění domu - pomocí připravených plánů nebo jednoduchého průvodce pomáhá optimalizovat nastavení času a teploty systému bez ztráty pocitu vysoké tepelné pohody.',
    appParagraphFourth:
      'Umožňuje snadno sledovat provoz zařízení v domácnosti.',
    appParagraphFifth: 'Umožňuje snadno sledovat náklady generované systémem.',
    appParagraphSixth:
      'Může flexibilně měnit provozní parametry systému zvýšením teploty, když uživatel vstoupí do určité zóny kolem domu, nebo snížením, když ji opustí.',
    appParagraphSeventh:
      'Umožňuje integrovat libovolný počet topných zařízení, takže je perfektní jako systém řízení teploty v domech a bytech.',

    productTitleFirst: 'Spolupracující produkty',
    productTitleSecond: 'v systému Smart ',
    veoTitle: 'VEO topná tyč',
    veoFirst:
      'Topná tyč VEO Moderní tvar krytu a elegantní přední panel se stmívajícím displejem skrývají delikátní zařízení. Dálkově ovládaná topná tyč VEO Smart má ve skutečnosti výkon až 2 000 W a jedinečné elektrické řešení mu umožňuje instalovat svisle i vodorovně, prakticky do každého radiátoru s topným médiem.',
    veoSecond:
      'Základní nastavení (teplota a jednoduchý časovač) jsou k dispozici na předním panelu, ale nejpohodlnější přístup k plné funkčnosti systému poskytuje mobilní aplikace TERMA Smart. Zařízení pracuje se senzory otevírání oken a dalším senzorem teploty a vlhkosti ze série SMART.',

    heatingTitle: 'Termostatická hlavice VAZ',
    heatingFirst:
      'Propracovaný design rodiny SMART, elegantní černá nebo nadčasová bílá opláštění jsou charakteristickými znaky termostatické hlavice VAZ. Spolu se stmívajícím displejem dodávají celému zařízení jemnost. Hlavice je poháněna vysoce výkonným bateriovým článkem, který stačí nabít jednou za celou topnou sezónu.',
    heatingSecond:
      'Extrémně snadná montáž a postup autokalibrace umožňují instalaci hlavice téměř do jakéhokoli radiátoru a s jakýmkoli typem termostatického ventilu. Základní regulace jsou k dispozici na panelu zařízení a mobilní aplikace TERMA Smart podporuje plnou funkčnost systému. Zařízení pracuje se senzory otevírání oken a dalším senzorem teploty a vlhkosti ze série SMART.',

    radiatorTitle: 'Radiátor VOLTAN',
    radiatorFirst:
      'Elektrický konvektor VOLTAN - moderní, snadno použitelný, efektivní a zároveň velmi plochý, téměř nerozeznatelný na pozadí stěny. Topení je vybaveno nízkoteplotním výměníkem tepla 2000 W a pokročilým regulátorem s vlastním algoritmem řízení učení.',
    radiatorSecond:
      'Základní regulace jsou k dispozici na panelu zařízení a mobilní aplikace TERMA Smart podporuje plnou funkčnost systému. Zařízení pracuje se senzory otevírání oken a dalším senzorem teploty a vlhkosti ze série SMART.',

    sensorTitle: 'Čidla',
    sensorFirst:
      'Senzory VTS snímače teploty a vlhkosti. Snadno instalovatelný dvoufunkční senzor neustále sleduje teplotu a vlhkost v místnosti a odesílá informace do topných zařízení, jakmile se teplota v kontrolované zóně změní o půl stupně.',
    sensorSecond:
      'Senzor otevření okna VWS. Pokud je okno otevřené, senzor okamžitě odešle informace, které vypnou topení v dané zóně. ',

    available: 'Jsme k dispozici 24/7',
    weWork:
      'Pracujeme od pondělí do pátku od 7:00 do 18:00. Kromě toho jsme k dispozici 24 hodin denně, 7 dní v týdnu, prostřednictvím mobilních telefonních čísel a e-mailu.',
    details: 'Firemní údaje',
    address: 'Czaple 100 80-298 Gdaňsk Polsko',
    nip: 'NIP:583-10-18-844',
    regon: 'REGON: 190558447',
    registration:
      'číslo registrace: GIOŚ: E0001379W I Sąd Rej. w Gdańsku, VIII Wydz. Gosp.',
    KRS: 'KRS № 0000069067',
    capital: 'Základní jmění: 2 360 500 PLN',
    account:
      'Číslo účtu: ING Bank Slaski S.A. Филиал в Гданьске 88 1050 1764 1000 0023 0692 5997 ',
    form: 'Kontaktní formulář',
    send: 'Poslat',
    terma: 'SPOLEČNOST TERMA',
    machinery: 'PROTLAKOVÉ STROJE ',
    services: 'PRŮMYSLOVÉ SLUŽBY ',
    galvanizing: 'GALVANOVNA',
    medical: 'REHABILITAČNÍ PŘÍSTROJE',
    sale: 'TOPENÁŘSKÉ VÝROBKY',
    //
    thermostatic_head: 'Termostatická Hlavice',
    temperature_sensor: 'Čidlo teploty',
    electric_heater: 'Elektrická topná tyč',
    electric_radiator: 'Elektrický radiátor',
    'window-sensor': 'Čidlo otevřených oken',
    buy_sensor: 'Buy sensor',
    buy_termostatic_head: 'Buy thermostatic head',
    buy_heating_element: 'Buy heating element',
    download: 'Product card',
    VAZ: './product_card/VAZ-v1_EN_20211021_cibto.pdf',
    VTS: './product_card/VTS-v1_EN_20211021_cibto.pdf',
    VOS: './product_card/VOS-v1_EN_20211021_cibto.pdf',
    VEO: './product_card/VEO-v6_EN_20211020_cibto.pdf',
    terma_text: 'TERMA',
    terma_link: 'http://en.termagroup.pl/',
    machinery_text: 'MACHINERY',
    machinery_link: 'http://www.termamax.pl/en/glowna',
    services_text: ' ',
    services_link: ' ',
    galwanic_text: ' ',
    galwanic_link: ' ',
    medical_text: 'MEDICAL PRODUCTS',
    medical_link: 'https://www.termamed.pl/en',
  },
  sk: {
    description: 'Opis systému',
    presetation: 'Prezentácia',
    aboutApp: 'O aplikácii',
    products: 'Produkty',
    contact: 'Kontakt',
    bannerFirst: 'Zoznam sa s rodinou',
    bannerSecond: 'našich produktov Wifi',
    slidTitleFirst: 'Opis systému',
    slidTitleSecond: 'Terma SMART WiFi',
    firstSlideTitle: 'Čo je Terma SMART',
    firstSlideFirst: 'Línia elektrických produktov riadených bezdrôtovo.',
    firstSlideSecond:
      'Je inovatívne navrhnutý riadiaci systém vykurovania miestnosti, ktorý možno ľahko prispôsobiť vašim potrebám, s výberom z troch typov zariadení a dvoch typov čidiel.',
    firstSlideThird:
      'Je systém, ktorý inteligentne reaguje na meniace sa podmienky a komunikáciu pomocou cloudu.',
    ///
    secondSlideTitle: 'Diaľkové ovládanie',
    secondSlideFirst:
      'Jedinečnou vlastnosťou systému Smart je, že všetky zariadenia komunikujú priamo s miestnym (domácim) routerom wifi - nie je teda potrebný žiadny samostatný riadiaci centrálny modul, čo znamená výraznú úsporu pri nákupe systému.',
    secondSlideSecond:
      'Systém je riadený bezplatnou ovládaciou aplikáciou TERMA Smart, ktorá je k dispozícii pre Android a iOS.',
    ///
    thirdSlideTitle: 'Dizajn a konštrukcia',
    thirdSlideFirst:
      'Moderný dizajn zdôrazňuje jedinečnosť každého zariadenia, podporuje ergonómiu užívania a zároveň spája celú rodinu produktov.',
    thirdSlideSecond:
      'Elegantnů čiernu a nadčasovou bielou možno obohatiť farebnými okrajmi a multifunkčné indikátory teploty sa prispôsobí montážnej polohe zariadenia.',
    thirdSlideThird:
      'Zariadenia majú výkon až 2 000 W a rôzne varianty elektrického pripojenia a vykurovacia tyč VEO je vybavená jedinečným konektorom Smart SPLIT.',
    ///
    fourthSlideTitle: 'Bezpečnosť a možnosti SMART',
    fourthSlideFirst:
      'Bezpečnosť užívateľa zaisťujú regulátory vybavené algoritmy riadenia teploty a každé vykurovacie zariadenie má špeciálne zvolenú tepelnú ochranu, aby sa zabránilo prehriatiu. Preddefinované ochranné funkcie, ako je AntiFrost a detektor otváranie okien, zostávajú aktívne na pozadí.',
    fourthSlideSecond:
      'Samoučiaca sa funkcia Early Start a tri prevádzkové režimy (komfortný, normálny a ekonomický) podporujú individuálne preferencie užívateľa.',
    ///
    appTitle: 'Aplikácia na mieru',
    appParagraphFrist:
      'Poskytuje pohodlie vzdialenej správy každého inteligentného wi-fi vykurovacieho zariadenia.',
    appParagraphSecond:
      'Uľahčuje správu domov rozdelením do zón a nastavením samostatných prevádzkových parametrov systému pre každú z nich.',
    appParagraphThird:
      'Poskytuje hmatateľné ekonomické výhody vďaka ľahkej optimalizácii spotreby energie na vykurovanie domu - pomocou pripravených plánov alebo jednoduchého sprievodcu pomáha optimalizovať nastavenie času a teploty systému bez straty pocitu vysokej tepelnej pohody.',
    appParagraphFourth:
      'Umožňuje ľahko sledovať prevádzku zariadení v domácnosti.',
    appParagraphFifth: 'Umožňuje ľahko sledovať náklady generované systémom.',
    appParagraphSixth:
      'Môže flexibilne meniť prevádzkové parametre systému zvýšením teploty, keď užívateľ vstúpi do určitej zóny okolo domu, alebo znížením, keď ju opustí.',
    appParagraphSeventh:
      'Umožňuje integrovať ľubovoľný počet vykurovacích zariadení, takže je perfektný ako systém riadenia teploty v domoch a bytoch.',

    productTitleFirst: 'Spolupracujúce produkty',
    productTitleSecond: 'v systéme Smart',
    veoTitle: 'VEO vykurovacia tyč',
    veoFirst:
      'Vykurovacia tyč VEO Moderný tvar krytu a elegantný predný panel sa stmívajúcím displejom skrývajú delikátnu zariadení. Diaľkovo ovládaná vykurovacia tyč VEO Smart má v skutočnosti výkon až 2 000 W a jedinečné elektrické riešenie mu umožňuje inštalovať zvisle aj vodorovne, prakticky do každého radiátora s vykurovacím médiom.',
    veoSecond:
      'Základné nastavenia (teplota a jednoduchý časovač) sú k dispozícii na prednom paneli, ale najpohodlnejšie prístup k plnej funkčnosti systému poskytuje mobilná aplikácia TERMA Smart. Zariadenie pracuje so senzormi otvárania okien a ďalším senzorom teploty a vlhkosti zo série SMART.',

    heatingTitle: 'Termostatická hlavica VAZ',
    heatingFirst:
      'Prepracovaný dizajn rodiny SMART, elegantná čierna alebo nadčasová biela opláštenia sú charakteristickými znakmi termostatické hlavice VAZ. Spolu so stmívajícím displejom dodávajú celému zariadeniu jemnosť. Hlavica je poháňaná vysoko výkonným batériovým článkom, ktorý stačí nabiť raz za celú vykurovaciu sezónu.',
    heatingSecond:
      'Extrémne jednoduchá montáž a postup autokalibrácie umožňujú inštaláciu hlavice takmer do akéhokoľvek radiátora a s akýmkoľvek typom termostatického ventilu. Základné regulácie sú k dispozícii na paneli zariadenia a mobilné aplikácie TERMA Smart podporuje plnú funkčnosť systému. Zariadenie pracuje so senzormi otváranie okien a ďalším senzorom teploty a vlhkosti zo série SMART.',

    radiatorTitle: 'Radiátor VOLTAN',
    radiatorFirst:
      'Elektrický konvektor VOLTAN - moderný, ľahko použiteľný, efektívny a zároveň veľmi plochý, takmer nerozoznateľný na pozadí steny. Kúrenie je vybavené nízkoteplotným výmenníkom tepla 2000 W a pokročilým regulátorom s vlastným algoritmom riadenia učenia.',
    radiatorSecond:
      'Základné regulácie sú k dispozícii na paneli zariadenia a mobilné aplikácie TERMA Smart podporuje plnú funkčnosť systému. Zariadenie pracuje so senzormi otváranie okien a ďalším senzorom teploty a vlhkosti zo série SMART.',

    sensorTitle: 'Čidlá',
    sensorFirst:
      'Senzory VTS snímače teploty a vlhkosti. Ľahko inštalovateľný dvoufunkční senzor neustále monitoruje teplotu a vlhkosť v miestnosti a odosiela informácie do vykurovacích zariadení, akonáhle sa teplota v kontrolovanej zóne zmení o pol stupňa.',
    sensorSecond:
      'Senzor otvorenie okna VWS Ak je okno otvorené, senzor okamžite odošle informácie, ktoré vypnú kúrenie v danej zóne. ',

    available: 'Sme k dispozícii 24/7',
    weWork:
      'Pracujeme od pondelka do piatku od 7:00 do 18:00. Okrem toho sme k dispozícii 24 hodín denne, 7 dní v týždni, prostredníctvom mobilných telefónnych čísel a e-mailu.',
    details: 'Firemné údaje',
    address: 'Czapla 100 80-298 Gdaňsk Poľsko',
    nip: 'NIP:583-10-18-844',
    regon: 'REGON: 190558447',
    registration: 'Číslo registrácie: Gios: E0001379W',
    KRS: 'KRS № 0000069067',
    capital: 'Základné imanie: 2 360 500 PLN',
    account:
      'Číslo účtu: ING Bank Slaski S.A. v Gdansku 88 1050 1764 1000 0023 0692 5997 ',
    form: 'Kontaktný formulár',
    send: 'Poslať',
    terma: 'SPOLOČNOSŤ TERMA',
    machinery: 'PROTLAKOVÉ STROJE',
    services: 'PRIEMYSELNÉ SLUŽBY',
    galvanizing: 'GALVANOVŇA',
    medical: 'REHABILITAČNÍ PRÍSTROJE',
    sale: 'KÚRENÁRSKE VÝROBKY',
    //
    thermostatic_head: 'Termostatická hlavica',
    temperature_sensor: 'Teplotný senzor',
    electric_heater: 'Elektrická vykorovacia tyč',
    electric_radiator: 'Elektrický radiátor',
    'window-sensor': 'Senzor otvorených okien',
    buy_sensor: 'Buy sensor',
    buy_termostatic_head: 'Buy thermostatic head',
    buy_heating_element: 'Buy heating element',
    download: 'Product card',
    VAZ: './product_card/VAZ-v1_EN_20211021_cibto.pdf',
    VTS: './product_card/VTS-v1_EN_20211021_cibto.pdf',
    VOS: './product_card/VOS-v1_EN_20211021_cibto.pdf',
    VEO: './product_card/VEO-v6_EN_20211020_cibto.pdf',
    terma_text: 'TERMA',
    terma_link: 'http://en.termagroup.pl/',
    machinery_text: 'MACHINERY',
    machinery_link: 'http://www.termamax.pl/en/glowna',
    services_text: ' ',
    services_link: ' ',
    galwanic_text: ' ',
    galwanic_link: ' ',
    medical_text: 'MEDICAL PRODUCTS',
    medical_link: 'https://www.termamed.pl/en',
  },
}

let domains = {
  pl: 'termasmart.pl',
  en: 'en.termasmart.com',
  de: 'de.termasmart.com',
  fr: 'fr.termasmart.com',
  ru: 'ru.termasmart.com',
  it: 'it.termasmart.com',
  cs: 'cs.termasmart.com',
  sk: 'sk.termasmart.com',
}

//translate
let $translate = $('.translate')
let $hostname = window.location.host.split('.')[
  window.location.host.split('.')[0].length > 2 ? 1 : 0
]
let $lang = $hostname

$('body').addClass($lang)

$translate.each(function () {
  $(this).attr('id') === $lang && $(this).addClass('active')
})

$('.lan').each(function () {
  $(this).attr('target')
    ? $(this).attr('href', langArr[$lang][$(this).attr('key')])
    : $(this).text(langArr[$lang][$(this).attr('key')])
  $('#lang').val($lang)
})

$('#lang').change(function () {
  let values = $('#lang :selected').val()

  $('body').removeAttr('class').addClass(values)
  $('.lan').each(function () {
    $(this).attr('target')
      ? $(this).attr('href', langArr[values][$(this).attr('key')])
      : $(this).text(langArr[values][$(this).attr('key')])
  })
  window.location.assign(`http://${domains[values]}`)

})
