const langArr = {
    en: {
        "description": "System description ",
        "presetation": "Presetation",
        "aboutApp": "About the App",
        "products": "Products",
        "contact": "Contact us",
        "bannerFirst": "Meet Terma WiFi",
        "bannerSecond": "system products",
        "slidTitleFirst": "Terma SMART WiFi",
        "slidTitleSecond": "system description",
        "firstSlideTitle": "What is Terma SMART",
        "firstSlideFirst": "it is a range of wirelessly controlled electric heating products,",
        "firstSlideSecond": "it is an innovatively designed heating control system that can be easily adapted to your needs, including a choice of three types of devices and two types of sensors,",
        "firstSlideThird": "It is a system that intelligently responds to changing conditions and communicates via the cloud.",
        ///
        "secondSlideTitle": "Remote control",
        "secondSlideFirst": "A unique feature of the Smart system is that all devices communicate directly with the local (home) wifi router - thus no separate control module is needed, which means a serious saving when purchasing the system.",
        "secondSlideSecond": "The system is managed by the free TERMA Smart control app, available for Android and iOS.",
        ///
        "thirdSlideTitle": "Design & construction",
        "thirdSlideFirst": "Modern design emphasizes the uniqueness of each device, supports ergonomics of use, and binds the entire family of products.",
        "thirdSlideSecond": "Elegant black and timeless white can be enriched with colored cover plates, and the multifunctional panel buttons will adjust to the mounting position of the device (horizontal or vertical)",
        "thirdSlideThird": "The power output of the devices goes up to 2,000W, feature a few variants of electrical connections, and the VEO heating element is equipped with a unique Smart SPLIT connector.",
        ///
        "fourthSlideTitle": "Safety and SMART options",
        "fourthSlideFirst": "The safety of the user is ensured by controllers equipped with temperature control algorithms, and each heating device has a specially selected thermal protection to prevent overheating. Predefined protection functions such as AntiFrost and the window opening detector remain active in the background.",
        "fourthSlideSecond": "The self-learning Adaptiv Start function and the three operating modes (Comfort, Balance and Economic) support individual user preferences.",
        ///
        "appTitle": "Dedicated app",
        "appParagraphFrist": "Gives the comfort of remote management of each Smart wi-fi heating device,",
        "appParagraphSecond": "facilitates home heating management by dividing the house into zones and setting separate system operating parameters for each of them,",
        "appParagraphThird": "provides tangible economic benefits by easily optimizing energy consumption for heating the house - using ready schedules or a simple scheduler helps to optimize the time and temperature settings of the system without losing the  thermal comfort,",
        "appParagraphFourth": "allows you to easily monitor the operation of devices throughout the house,",
        "appParagraphFifth": "allows you to easily monitor the costs generated by the system,",
        "appParagraphSixth": "allows flexible modification of the system's operating parameters by increasing the temperature when the User enters a specific zone or lowering it when away,",
        "appParagraphSeventh": "allows you to integrate any number of heating devices, making it perfect as a room temperature management system in flats and apartments.",

        "productTitleFirst": "The SMART",
        "productTitleSecond": "system products",
        "veoTitle": "VEO heating element",
        "veoFirst": "VEO heater The sophisticated shape of the housing and an elegant front panel with a fading display conceal a seemingly delicate device. In fact, the remotely controlled VEO Smart heating element has a power of up to 2000 W, and the unique electrical connection allows it to be installed both vertically and horizontally, almost in any radiator with a heating medium.",
        "veoSecond": "Basic adjustments (temperature and a simple timer) are available through the front panel, but the most convenient access to the full functionality of the system is provided by the TERMA Smart mobile application. The device works with window opening sensors and an additional temperature and humidity sensor from the SMART series.",

        "heatingTitle": "Thermostatic head",
        "heatingFirst": "The sophisticated design of the SMART family, elegant black or the timeless white of the housing are the hallmarks of the VAZ thermostatic head. Together with the fading display, they add subtlety to the entire device. The head is powered by a high-performance battery cell, which is charged on a single charge for the entire heating season.",
        "heatingSecond": "Extremely easy assembly and the auto-calibration procedure allow the head to be installed in almost any radiator and with any type of thermostatic valve. Basic regulations are available through the panel on the device, and the full functionality of the system is supported by the TERMA Smart mobile application. The device works with window opening sensors and an additional temperature and humidity sensor from the SMART series.",


        "radiatorTitle": "Radiator",
        "radiatorFirst": "Electric convector VOLTAN - modern, easy to use, efficient, and at the same time very flat, almost indistinguishable against the background of the wall. The heater is equipped with a low-temperature 2000 W heat exchanger and an advanced controller with a self-learning control algorithm.",
        "radiatorSecond": "Basic settings are available through the panel on the device, and the full functionality of the system is supported by the TERMA Smart mobile application. The device works with window opening sensors and an additional temperature and humidity sensor from the SMART series.",

        "sensorTitle": "Sensors",
        "sensorFirst": "VTS temperature and humidity sensor. An easy-to-install dual-function sensor constantly monitors the temperature and humidity in the room, sending information to the heating devices as soon as the temperature in the controlled zone changes by half a degree. ",
        "sensorSecond": "VWS open window sensor. When the window is opened, the sensor sends information immediately to switch off heating in a given zone.",

        "available": "We are available 24/7",
        "weWork": "We work from Monday to Friday from 07:00 to 18:00. In addition, we are available 24 hours a day, 7 days a week, using mobile phone numbers and via e-mail.",
        "details": "Company details",
        "address": "Czaple 100 80-298 Gdańsk Poland",
        "nip": "NIP:583-10-18-844",
        "regon": "REGON: 190558447",
        "registration": "Company registration: E0001379W I Sąd Rej. w Gdańsku, VIII Wydz. Gosp.",
        "KRS": "KRS nr 0000069067",
        "capital": "Capital: 2 360 500PLN",
        "account": "Bank account number: ING Bank Slaski S.A. Oddział w Gdańsku 88 1050 1764 1000 0023 0692 5997",
        "form": "Contact form",
        "send": "Send",
        "terma": "TERMA",
        "machinery": "CONSTRUCTION MACHINERY",
        "services": "INDUSTRIAL SERVICES",
        "galvanizing": "GALVANIZING",
        "medical": "MEDICAL PRODUCTS",
        "sale": "SALE OF RADIATORS",
    },
    de: {
        "description": "Systembeschreibung",
        "presetation": "Vorstellung",
        "aboutApp": "Über die Applikation",
        "products": "Produkte",
        "contact": "Kontakt",
        "bannerFirst": "Lernen Sie unsere WLAN",
        "bannerSecond": "Produktfamilie kennen",
        "slidTitleFirst": "Systembeschreibung",
        "slidTitleSecond": "Terma SMART WiFi",
        "firstSlideTitle": "Was ist Terma SMART",
        "firstSlideFirst": "Dies ist eine Auswahl ferngesteuerter Heizungsprodukte",
        "firstSlideSecond": "es ist ein innovativ konzipiertes Raumheizungsregelsystem, das sich dank einer Auswahl von drei Gerätetypen und zwei Sensortypen leicht an Ihre individuellen Bedürfnisse anpassen lässt",
        "firstSlideThird": "es ist ein System, das intelligent auf sich ändernde Bedingungen und Kommunikation über eine Cloud reagiert.",
        ///
        "secondSlideTitle": "Fernsteuerung",
        "secondSlideFirst": "Ein einzigartiges Merkmal des Smart-Systems ist, dass alle Geräte direkt mit dem lokalen (Heim-)WLAN-Router kommunizieren - somit wird kein separates Steuermodul benötigt, was erhebliche Einsparungen beim Kauf des Systems bedeutet.",
        "secondSlideSecond": "Zur Bedienung des Systems die kostenlose Steuerungs-App TERMA Smart benötigt, die für Android und iOS verfügbar ist.",
        ///
        "thirdSlideTitle": "Design und Konstruktion",
        "thirdSlideFirst": "Das moderne Design unterstreicht die Einzigartigkeit jedes Geräts und unterstützt die Ergonomie der Bedienung, gleichzeitig verbindet es die gesamte Produktfamilie.",
        "thirdSlideSecond": "Elegantes Schwarz und zeitloses Weiß können mit farbigen Overlays aufgewertet werden. Die Multifunktionsanzeige passt sich der Montageposition des Gerätes an.",
        "thirdSlideThird": "Die Geräte verfügen über eine Ausgangsleistung von bis zu 2.000 W und besitzen verschiedene elektrische Anschlussmöglichkeiten. Die Heizpatrone VEO ist mit dem einzigartigen Smart-SPLIT-Anschluss ausgestattet.",
        ///
        "fourthSlideTitle": "SMART Sicherheit und Optionen",
        "fourthSlideFirst": "Die Sicherheit des Benutzers wird durch die Steuerungen mittels Temperaturregelungsalgorithmen gewährleistet, und jedes Heizgerät verfügt über einen eingebauten, speziell ausgewählten Thermoschutz, der eine Überhitzung verhindert. Vordefinierte Schutzfunktionen wie AntiFrost und Fensteröffnungssensor sind permanent im Hintergrund aktiv.",
        "fourthSlideSecond": "Eine selbstlernende Adaptiv-Start-Funktion und drei Betriebsmodi (Komfort, Ausgewogen und Economy) unterstützen individuelle Benutzerpräferenzen.",
        ///
        "appTitle": "Maßgeschneiderte Applikation",
        "appParagraphFrist": "Ermöglicht Ihnen die bequeme Verwaltung eines beliebigen Smart-Wi-Fi-Heizgeräts aus der Ferne,",
        "appParagraphSecond": "macht die Verwaltung Ihres Hauses einfach, indem es in Zonen unterteilt wird und für jede Zone separate Systemparameter eingestellt werden,",
        "appParagraphThird": "bietet messbare wirtschaftliche Vorteile durch die einfache Optimierung des Energieverbrauchs für zum Beheizen Ihres Hauses - mit Hilfe von vorgefertigten Zeitplänen oder einem einfachen Assistenten hilft es, die Zeit- und Temperatureinstellungen des Systems zu optimieren, ohne dabei das Gefühl des hohen thermischen Komforts zu verlieren,",
        "appParagraphFourth": "ermöglicht Ihnen die einfache Überwachung der vom System erzeugten Kosten,",
        "appParagraphFifth": "ermöglicht Ihnen die einfache Überwachung der vom System erzeugten Kosten,",
        "appParagraphSixth": "kann die Betriebsparameter des Systems flexibel ändern und die Temperatur erhöhen, wenn der Benutzer eine bestimmte Zone im Haus betritt oder sie wieder absenken, wenn er sie verlässt,",
        "appParagraphSeventh": "ermöglicht die Integration beliebig vieler Heizgeräte und ist damit ideal für die Nutzung als Raumtemperatur-Management-System in Wohnungen und Appartements.",

        "productTitleFirst": "Produkte arbeiten im Smart",
        "productTitleSecond": "System zusammen",
        "veoTitle": "Heizpatrone VEO",
        "veoFirst": "Die raffinierte Form des Gehäuses und die elegante Frontplatte mit dimmbarem Display verbergen ein scheinbar filigranes Gerät. Die ferngesteuerte Heizpatrone VEO Smart hat eine Leistung von bis zu 2000 W. Dank ihres einzigartigen elektrischen Anschlusses kann sie sowohl vertikal als auch horizontal in praktisch jedem mit einem Heizmedium befüllten Heizkörper installiert werden.",
        "veoSecond": "Grundlegende Einstellungen (Temperatur und einfacher Timer) sind über die Frontplatte verfügbar, aber der bequemste Zugriff auf die volle Funktionalität des Systems erfolgt über die mobile Anwendung TERMA Smart. Das Gerät arbeitet mit Fensteröffnungssensoren und zusätzlichen Temperatur- und Feuchtigkeitssensoren der SMART-Serie.",

        "heatingTitle": "Thermostatkopf",
        "heatingFirst": "Das raffinierte Design der SMART-Familie, das elegante schwarze oder zeitlose weiße Gehäuse sind die charakteristischen Merkmale des VAZ-Thermostatkopfes. Zusammen mit dem dimmbaren Display verleihen sie dem ganzen Gerät eine subtile Raffinesse. Der Kopf wird von einer Hochleistungsbatteriezelle gespeist, die mit einer einzigen Ladung für die gesamte Heizsaison ausreicht.",
        "heatingSecond": "Durch die extrem einfache Montage und den Selbstkalibrierungsvorgang kann der Kopf in fast jeden Heizkörper und mit jedem Thermostatventiltyp installiert werden. Grundlegende Einstellungen sind über das Bedienfeld auf dem Gerät verfügbar und die volle Funktionalität des Systems wird durch die mobile Anwendung TERMA Smart unterstützt. Das Gerät arbeitet mit \"Geöffnete Fenster\" Sensoren und zusätzlichen Temperatur- und Feuchtigkeitssensoren der SMART-Serie zusammen.",


        "radiatorTitle": "Heizkörper",
        "radiatorFirst": "Elektrischer Konvektor VOLTAN - modern, einfach in der Bedienung, effizient und gleichzeitig sehr flach, fast unsichtbar auf der Wand. Der Heizkörper ist mit einem Niedertemperaturtauscher mit einer Leistung von 2000 W und einer fortschrittlichen Steuerung mit einem selbstlernenden Kontrollalgorithmus ausgestattet.",
        "radiatorSecond": "Grundlegende Regelungen sind über das Bedienfeld auf dem Gerät verfügbar und die volle Funktionalität des Systems wird durch die mobile Anwendung TERMA Smart unterstützt. Das Gerät arbeitet mit \"Geöffnete Fenster\" Sensoren und zusätzlichen Temperatur- und Feuchtigkeitssensoren der SMART-Serie zusammen.",

        "sensorTitle": "Temperatursonsoren",
        "sensorFirst": "Sensoren Temperatursensor und Feuchtigkeitssensor VTS. Der einfach zu montierende Doppelfunktionssensor überwacht permanent Raumtemperatur und Luftfeuchtigkeit. Er sendet Informationen an die Heizgeräte, sobald sich die Temperatur in der kontrollierten Zone nur um ein halbes Grad verändert.",
        "sensorSecond": "Sensor für \"Geöffnetes Fenster\" VWS. Sollte ein Fenster geöffnet werden, sendet der Sensor sofort eine Information, wodurch die Heizung in der betreffenden Zone ausgeschaltet wird.",

        "available": "Wir sind 24/7 für Sie erreichbar",
        "weWork": "Wir arbeiten von Montag bis Freitag von 7:00 bis 18:00 Uhr. Darüber hinaus sind wir 24 Stunden am Tag, 7 Tage die Woche über unsere Mobilfunknummern oder per E-Mail erreichbar.",
        "details": "Firmendaten",
        "address": "Czaple 100 80-298 Gdańsk Polen",
        "nip": "Ust.-Id.-Nr. PL583-10-28-844",
        "regon": "Gewerbenr.: 190558447",
        "registration": "GIOŚ: E0001379W I Registergericht zu Gdańsk, VIII Wydz. Gosp.",
        "KRS": "REG. Nr. 0000069067",
        "capital": "Stammkapitał:2 360 500 PLN",
        "account": "Banverbindung: ING Bank Slaski S.A. Oddział w Gdańsku 88 1050 1764 1000 0023 0692 5997",
        "form": "Kontaktformular",
        "send": "Senden",
        "terma": "TERMA GESELLSCHAFT",
        "machinery": "BAUMASCHINEN",
        "services": "INDUSTRIELLE DIENSTLEISTUNGEN",
        "galvanizing": "GALVANIK",
        "medical": "MEDIZINPRODUKTE",
        "sale": "VERTRIEB VON HEIZKÖRPERN",
    },
    ru: {
        "description": "Описание системы",
        "presetation": "Презентация",
        "aboutApp": "О приложении",
        "products": "Продукция",
        "contact": "Контакт",
        "bannerFirst": "Познакомьтесь с семeйством",
        "bannerSecond": "WiFi продуктов",
        "slidTitleFirst": "Описание системы",
        "slidTitleSecond": "Terma SMART WiFi",
        "firstSlideTitle": "Что такое Terma SMART",
        "firstSlideFirst": "Это выбор продуктов отопления с дистанционным управлением",
        "firstSlideSecond": "это инновационная система управления отоплением помещения, которую можно легко адаптировать к вашим потребностям, с выбором из трех типов устройств и двух типов датчиков",
        "firstSlideThird": "это система, которая разумно реагирует на изменение условий и коммуникации с помощью облака.",
        ///
        "secondSlideTitle": "Дистанционное управление",
        "secondSlideFirst": "Уникальной особенностью системы Smart является то, что все устройства напрямую взаимодействуют с локальным (домашним) WiFi - маршрутизатором-таким образом, вам не нужен отдельный модуль управления, и это означает серьезную экономию при покупке системы.",
        "secondSlideSecond": "Для управления системой используется бесплатное приложение управления Terma Smart, доступное для Android и iOS.",
        ///
        "thirdSlideTitle": "Дизайн и конструкция",
        "thirdSlideFirst": "Современный дизайн подчеркивает уникальность каждого устройства и поддерживает эргономику работы, в то же время он сочетает в себе все семейство продуктов.",
        "thirdSlideSecond": "Элегантный черный и неподвластный времени белый цвета могут быть дополнены цветными накладками, а многофункциональные кнопки на панели будут настраиваться в соответствии с положением установки устройства (горизонтальным или вертикальным).",
        "thirdSlideThird": "Устройства имеют мощность до 2000 w и различные варианты электрических подключений, а электронагреватель VEO оснащен уникальным разъемом Smart SPLIT.",
        ///
        "fourthSlideTitle": "Безопасность и опции SMART",
        "fourthSlideFirst": "За безопасностью пользователя следят контроллеры, оснащенные алгоритмами контроля температуры, и каждое отопительное оборудование имеет встроенную специально подобранную термозащиту для предотвращения перегрева. В фоновом режиме все время остаются активными предварительно определенные защитные функции, такие как антифриз (замерзание) и датчик открытия окна.",
        "fourthSlideSecond": "Самообучающаяся функция адаптивного запуска и три режима работы (комфортный, сбалансированный и экономичный) поддерживают индивидуальные предпочтения пользователя.",
        ///
        "appTitle": "Индивидуальное, специальное приложение",
        "appParagraphFrist": "Это дает удобство удаленного управления каждым электронагревателем Smart Wi-Fi,",
        "appParagraphSecond": "облегчает управление домом за счет разделения на зоны и установки отдельных параметров работы системы для каждой из них,",
        "appParagraphThird": "обеспечивает ощутимые экономические преимущества за счет простой оптимизации энергопотребления для отопления дома - использование готовых графиков или простого планировщика помогает оптимизировать временные и температурные настройки системы без потери теплового комфорта,",
        "appParagraphFourth": "позволяет легко контролировать работу устройств по всему дому,",
        "appParagraphFifth": "позволяет легко контролировать затраты, генерируемые системой,",
        "appParagraphSixth": "может гибко изменять рабочие параметры системы и повышать температуру, когда пользователь входит в определенную зону в доме, или снова опускать ее, когда он покидает ее,",
        "appParagraphSeventh": "позволяет интегрировать любое количество отопительных приборов, что делает его идеальным в качестве системы управления комнатной температурой в квартирах и аппартаментах.",

        "productTitleFirst": "Продукты SMART",
        "productTitleSecond": "",
        "veoTitle": "Электронагреватель VEO",
        "veoFirst": "За сложной формой корпуса и элегантной передней панелью имеющей затемнённый дисплей скрывается, казалось бы, хрупкое устройство. Фактически, дистанционно управляемый электронагреватель VEO Smart имеет мощность до 2000 w, а уникальное электрическое соединение позволяет устанавливать его как вертикально, так и горизонтально, практически в каждом радиаторе с теплоносителем.",
        "veoSecond": "Основные настройки (температура и простой таймер) доступны через переднюю панель, но наиболее удобный доступ к полному функционалу системы обеспечивает мобильное приложение TERMA Smart. Устройство работает с датчиками открывания окон и дополнительным датчиком температуры и влажности из серии SMART.",

        "heatingTitle": "Термоголовка",
        "heatingFirst": "Изысканный дизайн семейства SMART, элегантный черный или неподвластный времени белый корпус являются отличительными чертами термостатической головки VAZ. Вместе с заттемняющимся дисплеем они добавляют тонкости всему устройству. Головка питается от высокопроизводительного аккумуляторного элемента, которая заряжается одним зарядом в течение всего отопительного сезона.",
        "heatingSecond": "Чрезвычайно простая сборка и процедура автоматической калибровки позволяют устанавливать головку практически в любой радиатор и с любым типом термостатического клапана. Основные правила доступны через панель на устройстве, а полная функциональность системы поддерживается мобильным приложением TERMA Smart. Устройство работает с датчиками открывания окон и дополнительным датчиком температуры и влажности из серии SMART.",


        "radiatorTitle": "Радиатор",
        "radiatorFirst": "Электрический конвектор VOLTAN-современный, простой в использовании, эффективный, но очень плоский, почти не различимый на фоне стены. Нагреватель оснащен низкотемпературным теплообменником мощностью 2000w и усовершенствованным контроллером с самообучающимся алгоритмом управления.",
        "radiatorSecond": "Основные настройки доступны через панель на устройстве, а полную функциональность системы поддерживает мобильное приложение Terma Smart. Устройство работает с датчиками открытия окна и дополнительным датчиком температуры и влажности серии SMART.",

        "sensorTitle": "Датчики",
        "sensorFirst": "Датчик температуры и влажности VTS. Простой в установке двухфункциональный датчик постоянно контролирует температуру и влажность в помещении, отправляя информацию в отопительные приборы, как только температура в контролируемой зоне изменяется на полградуса. ",
        "sensorSecond": "VWS датчик открытого окна. Когда окно открывается, датчик немедленно отправляет информацию об отключении обогрева в данной зоне ",

        "available": "Мы доступны 24/7",
        "weWork": "Работаем с понедельника по пятницу с 07:00 до 18:00. Кроме того, мы доступны 24 часа в сутки, 7 дней в неделю, используя номера мобильных телефонов и электронную почту.",
        "details": "Данные компании",
        "address": "Czaple 100 80-298 Гданьск Польша",
        "nip": "NIP:583-10-18-844",
        "regon": "REGON: 190558447",
        "registration": "Рег. № GIOŚ: E0001379W I Sąd Rej. w Gdańsku, VIII Wydz. Gosp.",
        "KRS": "KRS № 0000069067",
        "capital": "Капитал: 2 360 500 PLN",
        "account": "Номер банковского счета: ING Bank Slaski S.A. Филиал в Гданьске 88 1050 1764 1000 0023 0692 5997 ",
        "form": "Форма обратной связи",
        "send": "Отправить",
        "terma": "TERMA",
        "machinery": "СТРОИТЕЛЬНАЯ ТЕХНИКА",
        "services": "ПРОМЫШЛЕННЫЕ УСЛУГИ",
        "galvanizing": "ГАЛЬВАНИЗАЦИЯ",
        "medical": "МЕДИЦИНСКИЕ ИЗДЕЛИЯ",
        "sale": "ПРОДАЖА РАДИАТОРОВ"
    },
    pl: {
        "description": "Opis systemu",
        "presetation": "Prezentacja",
        "aboutApp": "O aplikacji",
        "products": "Produkty",
        "contact": "Kontakt",
        "bannerFirst": "Poznaj rodzinę naszych",
        "bannerSecond": "produktów WiFi",
        "slidTitleFirst": "Opis systemu",
        "slidTitleSecond": "Terma SMART WiFi",
        "firstSlideTitle": "Czym jest Terma SMART",
        "firstSlideFirst": "To gama elektrycznych produktów grzewczych sterowanych bezprzewodowo,",
        "firstSlideSecond": "to innowacyjnie zaprojektowany system sterowania ogrzewaniem pomieszczeń, który dopasujesz z łatwością do swoich potrzeb, mając do wyboru trzy typy urządzeń i dwa rodzaje czujników,",
        "firstSlideThird": "to system inteligentnie reagujący na zmieniające się warunki i komunikacja z wykorzystaniem chmury.",
        ///
        "secondSlideTitle": "Zdalne sterowanie",
        "secondSlideFirst": "Unikalną cechą systemu Smart jest to, że wszystkie urządzenia komunikują się bezpośrednio z lokalnym (domowym) routerem wifi - dzięki temu nie jest potrzebny żaden oddzielny moduł kontrolny, a to oznacza poważną oszczędność przy zakupie systemu.",
        "secondSlideSecond": "Do zarządzania systemem służy darmowa aplikacja sterująca TERMA Smart, dostępna dla systemów Android oraz iOS. ",
        ///
        "thirdSlideTitle": "Design i konstrukcja",
        "thirdSlideFirst": "Nowoczesny design podkreśla unikalność każdego z urządzeń wspierając ergonomię użytkowania, a jednocześnie spaja całą rodzinę produktów.",
        "thirdSlideSecond": "Elegancką czerń i ponadczasową biel można wzbogacić kolorowymi nakładkami, a wielofunkcyjny wskaźnik dostosuje się do pozycji montażu urządzenia.",
        "thirdSlideThird": "Urządzenia dysponują mocą do 2 000W i różnymi wariantami przyłączy elektrycznych, a grzałka VEO wyposażona jest w unikalne złącze Smart SPLIT.",
        ///
        "fourthSlideTitle": "Bezpieczeństwo i opcje SMART",
        "fourthSlideFirst": "Nad bezpieczeństwem użytkownika czuwają sterowniki wyposażone w algorytmy kontrolujące temperaturę, a każde z urządzeń grzewczych posiada wbudowane specjalnie dobrane zabezpieczenie termiczne, zapobiegające przegrzaniu. W tle cały czas pozostają aktywne zdefiniowane wstępnie funkcje ochronne, jak AntiFrost oraz czujnik otwarcia okna.",
        "fourthSlideSecond": "Samoucząca się funkcja Wcześniejszy Start oraz trzy tryby pracy (Komfortowy, Zbalansowany i Ekonomiczny) wspierają indywidualne preferencje użytkownika",
        ///
        "appTitle": "Aplikacja uszyta na miarę",
        "appParagraphFrist": "Daje komfort zdalnego zarządzania każdym urządzeniem grzewczym Smart wi-fi,",
        "appParagraphSecond": "ułatwia zarządzanie domem poprzez podział na strefy i ustalanie dla każdej z nich odrębnych parametrów pracy systemu,",
        "appParagraphThird": "dostarcza wymiernych korzyści ekonomicznych poprzez łatwą optymalizację zużycia energii na ogrzewanie domu – korzystając z gotowych harmonogramów lub z prostego kreatora pomaga zoptymalizować ustawienia czasu i temperatury pracy systemu, nie tracąc poczucia wysokiego komfortu cieplnego,",
        "appParagraphFourth": "pozwala łatwo monitorować pracę urządzeń w całym domu,",
        "appParagraphFifth": "pozwala łatwo monitorować koszty generowane przez system,",
        "appParagraphSixth": "może elastycznie modyfikować parametry pracy systemu podwyższając temperaturę kiedy Użytkownik wkracza w określoną strefę wokół domu lub obniżając, kiedy ją opuszcza,",
        "appParagraphSeventh": "pozwala zintegrować dowolną ilość urządzeń grzewczych, dzięki czemu doskonale sprawdzi się jako system zarządzania temperaturą pomieszczeń w mieszkaniach i apartamentach.",
        ///
        "productTitleFirst": "Produkty współpracujące",
        "productTitleSecond": "w systemie Smart",
        "veoTitle": "Grzałka VEO",
        "veoFirst": "Grzałka VEO Wyrafinowany kształt obudowy i elegancki panel frontowy z przygasającym wyświetlaczem kryją w sobie delikatne z pozoru urządzenie. W rzeczywistości zdalnie sterowana grzałka VEO Smart dysponuje mocą do 2000 W, a unikalne przyłącze elektryczne pozwala zainstalować ją zarówno w pionie, jak i w poziomie, praktycznie w każdym grzejniku z czynnikiem grzewczym.",
        "veoSecond": "Podstawowe regulacje (temperatura i prosty Timer) dostępne są poprzez panel frontowy, ale najwygodniejszy dostęp do pełnej funkcjonalności systemu daje aplikacja mobilna TERMA Smart. Urządzenie współpracuje z czujnikami otwarcia okna oraz dodatkowym czujnikiem temperatury i wilgotności serii SMART.",

        "heatingTitle": "Głowica",
        "heatingFirst": "Wyrafinowane wzornictwo rodziny SMART, elegancka czerń lub ponadczasowa biel obudowy to cechy charakterystyczne głowicy termostatycznej VAZ. Razem przygasającym wyświetlaczem nadają subtelności całemu urządzeniu. Głowica zasilana jest wysokowydajnym ogniwem akumulatorowym, którego pojedyncze ładowanie wystarcza na cały sezon grzewczy.",
        "heatingSecond": "Niezwykle łatwy montaż oraz procedura autokalibracji pozwalają na instalację głowicy niemal w każdym grzejniku i z każdym typem zaworu termostatycznego. Podstawowe regulacje dostępne są poprzez panel na urządzeniu, a pełną funkcjonalność systemu obsługuje aplikacja mobilna TERMA Smart. Urządzenie współpracuje z czujnikami otwarcia okna oraz dodatkowym czujnikiem temperatury i wilgotności serii SMART.",

        "radiatorTitle": "Grzejnik",
        "radiatorFirst": "Elektryczny konwektor VOLTAN - nowoczesny, prosty w obsłudze, wydajny, a jednocześnie bardzo płaski, niemal niewyróżniający się na tle ściany. Grzejnik wyposażony jest w niskotemperaturowy wymiennik o mocy 2000 W i zaawansowany sterownik z samouczącym się algorytmem kontrolnym.",
        "radiatorSecond": "Podstawowe regulacje dostępne są poprzez panel na urządzeniu, a pełną funkcjonalność systemu obsługuje aplikacja mobilna TERMA Smart. Urządzenie współpracuje z czujnikami otwarcia okna oraz dodatkowym czujnikiem temperatury i wilgotności serii SMART.",

        "sensorTitle": "Czujniki",
        "sensorFirst": "Czujniki Czujnik temperatury i wilgotności VTS. Łatwy w montażu dwufunkcyjny czujnik stale monitoruje temperaturę i wilgotność w pomieszczeniu, wysyłając informacje do urządzeń grzewczych, jeśli tylko temperatura w kontrolowanej strefie zmieni się o pół stopnia.",
        "sensorSecond": "Czujnik otwarcia okna VWS. W przypadku otwarcia okna czujnik natychmiast wysyła informację powodującą wyłączenie ogrzewania w danej strefie.",

        "available": "Jesteśmy dostępni 24/7",
        "weWork": "Pracujemy od poniedziałku do piątku od 07:00 do 18:00. Ponadto jesteśmy dostępni 24 h na dobę przez 7 dni w tygodniu pod numerami telefonów komórkowych oraz za pośrednictwem poczty e-mail.",
        "details": "Dane firmy",
        "address": "Czaple 100 80-298 Gdańsk Polska",
        "nip": "NIP:583-10-18-844",
        "regon": "REGON: 190558447",
        "registration": "nr rej. GIOŚ: E0001379W I Sąd Rej. w Gdańsku, VIII Wydz. Gosp.",
        "KRS": "KRS nr 0000069067",
        "capital": "Kapitał:2 360 500PLN",
        "account": "Nr konta bankowego: ING Bank Slaski S.A. Oddział w Gdańsku 88 1050 1764 1000 0023 0692 5997",
        "form": "Formularz kontaktowy",
        "send": "Wyślij",
        "terma": "TERMA SPÓŁKA",
        "machinery": "MASZYNY BUDOWLANE",
        "services": "USŁUGI PRZEMYSŁOWE",
        "galvanizing": "GALWANIZERNIA",
        "medical": "PRODUKTY MEDYCZNE",
        "sale": "WYPRZEDAŻ GRZEJNIKÓW"
    }
};


// let $href = document.location.pathname;

let $translate = $('.translate');
let $lang = navigator.language.slice(0, 2);

$('body').addClass($lang);

$translate.each(function () {
    $(this).attr('id') === $lang && $(this).addClass('active');
});
$('.lan').each(function () {
    $(this).text(langArr[$lang][$(this).attr('key')]);
});


$translate.click(function () {
    $translate.each(function () {
        $(this).removeClass('active');
    });

    let lang = $(this).attr('id');

    $(this).addClass('active');

    $('.lan').each(function () {
        $(this).text(langArr[lang][$(this).attr('key')]);
    });
});
